const wordList = [
    // Level 3-01
    { section: "3-01", en: "maneuver", ja: "作戦、策略、巧妙に動かす", ex: "He made a clever maneuver to win.", exJa: "彼は勝つために巧妙な作戦を立てた。" },
    { section: "3-01", en: "outbreak", ja: "(病気・戦争などの)突発、発生", ex: "The outbreak of the flu spread quickly.", exJa: "インフルエンザの突発的発生が急速に広がった。" },
    { section: "3-01", en: "infection", ja: "感染、伝染病", ex: "Wash your hands to prevent infection.", exJa: "感染を防ぐために手を洗いましょう。" },
    { section: "3-01", en: "strategy", ja: "戦略、計画", ex: "We need a new marketing strategy.", exJa: "我々には新しいマーケティング戦略が必要だ。" },
    { section: "3-01", en: "contend", ja: "戦う、主張する", ex: "She had to contend with many difficulties.", exJa: "彼女は多くの困難と戦わなければならなかった。" },
    { section: "3-01", en: "appliance", ja: "器具、家電製品", ex: "Refrigerators are essential kitchen appliances.", exJa: "冷蔵庫は必須の家電製品だ。" },
    { section: "3-01", en: "deploy", ja: "配置する、展開する", ex: "The army was deployed to the border.", exJa: "軍隊が国境に配置された。" },
    { section: "3-01", en: "extract", ja: "抽出する、取り出す", ex: "Scientists extract oil from plants.", exJa: "科学者たちは植物から油を抽出する。" },
    { section: "3-01", en: "scheme", ja: "計画、陰謀", ex: "They hatched a scheme to rob the bank.", exJa: "彼らは銀行を襲う陰謀を企てた。" },
    { section: "3-01", en: "affirm", ja: "断言する、肯定する", ex: "He affirmed his commitment to the project.", exJa: "彼はプロジェクトへのコミットメントを断言した。" },
    { section: "3-01", en: "evaporate", ja: "蒸発する、消え去る", ex: "Water evaporates when heated.", exJa: "水は熱せられると蒸発する。" },
    { section: "3-01", en: "commute", ja: "通勤・通学する", ex: "It takes an hour to commute to work.", exJa: "通勤に1時間かかる。" },
    { section: "3-01", en: "tactic", ja: "戦術、駆け引き", ex: "Their negotiation tactic worked well.", exJa: "彼らの交渉の駆け引きがうまくいった。" },
    { section: "3-01", en: "drift", ja: "漂う、漂流する", ex: "The boat began to drift out to sea.", exJa: "ボートが海へ向かって漂流し始めた。" },
    { section: "3-01", en: "cue", ja: "合図、ヒント", ex: "Wait for my cue before speaking.", exJa: "話す前に私の合図を待て。" },
    { section: "3-01", en: "activate", ja: "作動させる、活性化する", ex: "Press the button to activate the alarm.", exJa: "アラームを作動させるにはボタンを押して。" },
    { section: "3-01", en: "presume", ja: "推定する、思う", ex: "I presume you are tired from the trip.", exJa: "旅行でお疲れのことと推測します。" },
    { section: "3-01", en: "contemplate", ja: "熟考する、じっくり考える", ex: "He contemplated his future career.", exJa: "彼は自分の将来のキャリアについて熟考した。" },
    { section: "3-01", en: "molecule", ja: "分子", ex: "Water is made of molecules.", exJa: "水は分子からできている。" },
    { section: "3-01", en: "stroke", ja: "脳卒中、一撃、なでること", ex: "He suffered a minor stroke last year.", exJa: "彼は昨年軽い脳卒中を患った。" },
    { section: "3-01", en: "stray", ja: "迷い出る、脱線する", ex: "A stray dog wandered into our yard.", exJa: "野良犬が私たちの庭に迷い込んできた。" },
    { section: "3-01", en: "orbit", ja: "軌道、軌道を周回する", ex: "The satellite entered into orbit.", exJa: "衛星が軌道に乗った。" },
    { section: "3-01", en: "rebel", ja: "反逆者、反逆する", ex: "They rebelled against the unfair tax.", exJa: "彼らは不当な税金に対して反逆した。" },
    { section: "3-01", en: "stroll", ja: "ぶらぶら歩く、散歩", ex: "We took a stroll along the beach.", exJa: "私たちは海岸に沿って散歩した。" },
    { section: "3-01", en: "deteriorate", ja: "悪化する", ex: "His health began to deteriorate.", exJa: "彼の健康状態が悪化し始めた。" },
    { section: "3-01", en: "descend", ja: "下る、降りる", ex: "The plane started to descend.", exJa: "飛行機が下降し始めた。" },
    { section: "3-01", en: "chronic", ja: "慢性の", ex: "She suffers from chronic back pain.", exJa: "彼女は慢性的な腰痛に苦しんでいる。" },
    { section: "3-01", en: "inquire", ja: "尋ねる、問い合わせる", ex: "I called to inquire about the schedule.", exJa: "私はスケジュールについて問い合わせるために電話した。" },
    { section: "3-01", en: "radiation", ja: "放射線、放射能", ex: "Exposure to radiation is dangerous.", exJa: "放射線への被曝は危険だ。" },
    { section: "3-01", en: "combat", ja: "戦闘、格闘する", ex: "They are fighting to combat poverty.", exJa: "彼らは貧困と戦うために奮闘している。" },
    { section: "3-01", en: "proclaim", ja: "宣言する、公表する", ex: "The president proclaimed a state of emergency.", exJa: "大統領は非常事態を宣言した。" },
    { section: "3-01", en: "tissue", ja: "(生物の)組織、ティッシュ", ex: "Muscle tissue needs protein to grow.", exJa: "筋肉組織の成長にはタンパク質が必要だ。" },
    { section: "3-01", en: "swell", ja: "膨らむ、増大する", ex: "Her ankle began to swell after the injury.", exJa: "怪我の後、彼女の足首が腫れ始めた。" },
    { section: "3-01", en: "boast", ja: "自慢する", ex: "He loves to boast about his success.", exJa: "彼は自分の成功を自慢するのが好きだ。" },
    { section: "3-01", en: "conceive", ja: "心に抱く、思いつく", ex: "I can't conceive how he did it.", exJa: "彼がそれをどうやったのか私には想像もつかない。" },
    { section: "3-01", en: "stumble", ja: "つまずく、偶然見つける", ex: "I stumbled upon an old diary.", exJa: "私は古い日記を偶然見つけた。" },
    { section: "3-01", en: "influx", ja: "流入", ex: "There was an influx of tourists.", exJa: "観光客の大量流入があった。" },
    { section: "3-01", en: "scar", ja: "傷跡、心の傷", ex: "The burn left a small scar.", exJa: "その火傷は小さな傷跡を残した。" },
    { section: "3-01", en: "retreat", ja: "後退する、引きこもる", ex: "The army was forced to retreat.", exJa: "軍は撤退を余儀なくされた。" },
    { section: "3-01", en: "epidemic", ja: "伝染病の流行", ex: "An epidemic of flu swept the city.", exJa: "インフルエンザの流行が街を席巻した。" },
    { section: "3-01", en: "alternative", ja: "代わりの、選択肢", ex: "Is there an alternative solution?", exJa: "別の解決策はありますか？" },
    { section: "3-01", en: "paralyze", ja: "まひさせる", ex: "The heavy snow paralyzed traffic.", exJa: "大雪が交通をまひさせた。" },
    { section: "3-01", en: "relocate", ja: "移転する、引っ越す", ex: "The company plans to relocate its office.", exJa: "会社はオフィスを移転する予定だ。" },

    // Level 3-02
    { section: "3-02", en: "apprehension", ja: "懸念、不安、逮捕", ex: "She felt a sense of apprehension.", exJa: "彼女は不安感を抱いた。" },
    { section: "3-02", en: "obesity", ja: "肥満", ex: "Childhood obesity is a growing problem.", exJa: "小児肥満は深刻化している問題だ。" },
    { section: "3-02", en: "fatigue", ja: "疲労", ex: "Driving while fatigue is dangerous.", exJa: "疲労状態での運転は危険だ。" },
    { section: "3-02", en: "perpetual", ja: "永続的な、絶え間ない", ex: "They live in perpetual fear.", exJa: "彼らは絶え間ない恐怖の中で暮らしている。" },
    { section: "3-02", en: "sustain", ja: "維持する、支える", ex: "Can the earth sustain more people?", exJa: "地球はさらに多くの人を養い支えることができるか？" },
    { section: "3-02", en: "bewildered", ja: "戸惑った、面食らった", ex: "He looked bewildered by the question.", exJa: "彼はその質問に戸惑っているように見えた。" },
    { section: "3-02", en: "dizzy", ja: "めまいがする", ex: "The high altitude made me dizzy.", exJa: "高地のためにめまいがした。" },
    { section: "3-02", en: "sniff", ja: "くんくん嗅ぐ、鼻をすする", ex: "The dog sniffed at the door.", exJa: "犬がドアのにおいをくんくんとかいだ。" },
    { section: "3-02", en: "sequence", ja: "連続、順序", ex: "Follow the instructions in sequence.", exJa: "指示に従って順番通りに進めてください。" },
    { section: "3-02", en: "successive", ja: "連続した", ex: "It rained for three successive days.", exJa: "3日連続で雨が降った。" },
    { section: "3-02", en: "resent", ja: "憤慨する、恨む", ex: "She resented being treated like a child.", exJa: "彼女は子供扱いされることに憤慨した。" },
    { section: "3-02", en: "empathy", ja: "共感、感情移入", ex: "Good leaders show empathy for others.", exJa: "優れたリーダーは他者への共感を示す。" },
    { section: "3-02", en: "nourish", ja: "栄養を与える、育む", ex: "Breast milk nourishes the baby.", exJa: "母乳が赤ちゃんの栄養を育む。" },
    { section: "3-02", en: "hospitality", ja: "手厚いもてなし、歓待", ex: "Thank you for your warm hospitality.", exJa: "温かいおもてなしをありがとうございます。" },
    { section: "3-02", en: "remedy", ja: "治療法、改善策", ex: "There is no simple remedy for this.", exJa: "これに対する簡単な解決策はない。" },
    { section: "3-02", en: "frail", ja: "虚弱な、壊れやすい", ex: "He is growing old and frail.", exJa: "彼は年老いて体が弱くなってきている。" },
    { section: "3-02", en: "drain", ja: "排出する、疲れ果てさせる", ex: "The long trip drained his energy.", exJa: "長い旅行で彼のエネルギーがすっかり奪われた。" },
    { section: "3-02", en: "fierce", ja: "激しい、凶暴な", ex: "There was fierce competition for the job.", exJa: "その仕事を手に入れるための激しい競争があった。" },
    { section: "3-02", en: "haunt", ja: "(幽霊などが)出没する、つきまとう", ex: "Memories of the accident haunt him.", exJa: "事故の記憶が彼につきまとっている。" },
    { section: "3-02", en: "sympathetic", ja: "同情的な、共感する", ex: "Friends were very sympathetic.", exJa: "友人たちはとても同情だった。" },
    { section: "3-02", en: "persist", ja: "固執する、持続する", ex: "If the symptoms persist, see a doctor.", exJa: "症状が続く場合は医師の診察を受けてください。" },
    { section: "3-02", en: "isolate", ja: "隔離する、孤立させる", ex: "Patients with the virus were isolated.", exJa: "ウイルス患者は隔離された。" },
    { section: "3-02", en: "shrug", ja: "肩をすくめる", ex: "He just shrugged his shoulders.", exJa: "彼はただ肩をすくめた。" },
    { section: "3-02", en: "intervene", ja: "介入する", ex: "Police had to intervene in the fight.", exJa: "警察がその喧嘩に介入せざるを得なかった。" },
    { section: "3-02", en: "retain", ja: "保持する、心にとどめる", ex: "Try to retain what you have learned.", exJa: "学んだことをしっかり心にとどめておきなさい。" },
    { section: "3-02", en: "physician", ja: "医師、内科医", ex: "She consulted a physician about her cough.", exJa: "彼女は咳について医師に相談した。" },
    { section: "3-02", en: "sarcastic", ja: "皮肉な、嫌味な", ex: "He made a sarcastic remark.", exJa: "彼は皮肉な発言をした。" },
    { section: "3-02", en: "diagnose", ja: "診断する", ex: "He was diagnosed with pneumonia.", exJa: "彼は肺炎と診断された。" },
    { section: "3-02", en: "recipient", ja: "受取人", ex: "She was the recipient of the award.", exJa: "彼女はその賞の受賞者だった。" },
    { section: "3-02", en: "provoke", ja: "引き起こす、挑発する", ex: "His remarks provoked an angry response.", exJa: "彼の発言が怒りの反応を引き起こした。" },
    { section: "3-02", en: "withstand", ja: "耐える、抵抗する", ex: "The building can withstand earthquakes.", exJa: "その建物は地震に耐えることができる。" },
    { section: "3-02", en: "gratitude", ja: "感謝", ex: "I expressed my deep gratitude to them.", exJa: "私は彼らに深い感謝の意を表した。" },
    { section: "3-02", en: "humiliate", ja: "恥をかかせる、屈辱を与える", ex: "He felt humiliated by the failure.", exJa: "彼はその失敗で恥をかかされたと感じた。" },
    { section: "3-02", en: "console", ja: "慰める", ex: "Nothing could console her after the loss.", exJa: "その喪失の後、彼女を慰めるものは何もなかった。" },
    { section: "3-02", en: "numb", ja: "麻痺した、感覚のない", ex: "My fingers were numb with cold.", exJa: "寒さで指の感覚がなかった。" },
    { section: "3-02", en: "undergo", ja: "経験する、受ける", ex: "She had to undergo surgery.", exJa: "彼女は手術を受けなければならなかった。" },
    { section: "3-02", en: "prescribe", ja: "処方する、指示する", ex: "The doctor prescribed some medicine.", exJa: "医師が薬を処方してくれた。" },
    { section: "3-02", en: "sewage", ja: "下水、汚水", ex: "The city lacks proper sewage treatment.", exJa: "その都市は適切な下水処理が不足している。" },
    { section: "3-02", en: "transplant", ja: "移植、移植する", ex: "He received a heart transplant.", exJa: "彼は心臓移植を受けた。" },
    { section: "3-02", en: "genetic", ja: "遺伝子の", ex: "It is a rare genetic disorder.", exJa: "それは珍しい遺伝性疾患だ。" },
    { section: "3-02", en: "dismay", ja: "落胆、失望させる", ex: "To my dismay, I missed the train.", exJa: "がっかりしたことに、私は電車に乗り遅れた。" },
    { section: "3-02", en: "immune", ja: "免疫のある、影響を受けない", ex: "Babies are immune to some diseases.", exJa: "赤ちゃんならではの免疫がある病気もある。" },
    { section: "3-02", en: "circulate", ja: "循環する、流通する", ex: "Blood circulates through the body.", exJa: "血液は体内を循環する。" },
    { section: "3-02", en: "sanitary", ja: "衛生的な、清潔な", ex: "Ensure you maintain sanitary conditions.", exJa: "衛生的な環境を保つようにしなさい。" },
    { section: "3-02", en: "durable", ja: "耐久性のある、長持ちする", ex: "This material is very durable.", exJa: "この素材は非常に耐久性がある。" },
    { section: "3-02", en: "terminal", ja: "末期の、終わりの、ターミナル", ex: "He is facing a terminal illness.", exJa: "彼は末期の病気と直面している。" },
    { section: "3-02", en: "perspire", ja: "汗をかく", ex: "I tend to perspire a lot when running.", exJa: "走るときにたくさん汗をかく傾向がある。" },
    { section: "3-02", en: "harass", ja: "嫌がらせをする、悩ませる", ex: "Workers should not be harassed.", exJa: "労働者が嫌がらせを受けてはならない。" },
    { section: "3-02", en: "distress", ja: "苦しみ、悲嘆、悩ませる", ex: "The news caused her great distress.", exJa: "そのニュースは彼女をひどく悲嘆に暮れさせた。" },

    // Level 3-03 〜 3-13 のデータ
    { section: "3-03", en: "treaty", ja: "条約、協定", ex: "The two countries signed a peace treaty.", exJa: "両国は平和条約に署名した。" },
    { section: "3-04", en: "hazard", ja: "危険、危険要素", ex: "Smoking is a health hazard.", exJa: "喫煙は健康上の危険要因だ。" },
    { section: "3-05", en: "momentum", ja: "勢い、弾み", ex: "The campaign is gaining momentum.", exJa: "キャンペーンは勢いを増している。" },
    { section: "3-06", en: "distract", ja: "（気を）散らす、紛らわす", ex: "Don't distract me while I'm working.", exJa: "仕事中だから気を散らさないでくれ。" },
    { section: "3-07", en: "overlap", ja: "重複する、重なり合う", ex: "Our schedules overlap next week.", exJa: "来週、私たちのスケジュールが重なっている。" },
    { section: "3-08", en: "competence", ja: "能力、適性", ex: "He demonstrated high professional competence.", exJa: "彼は高い専門的能力を示した。" },
    { section: "3-09", en: "shrink", ja: "縮む、縮小する", ex: "This wool sweater will shrink in hot water.", exJa: "このウールのセーターは熱いお湯で縮む。" },
    { section: "3-10", en: "manipulate", ja: "操る、巧みに扱う", ex: "He knows how to manipulate data.", exJa: "彼はデータを巧みに扱う方法を知っている。" },
    { section: "3-11", en: "supplement", ja: "補足、サプリメント、補う", ex: "I take a daily vitamin supplement.", exJa: "私は毎日のビタミンサプリメントを摂っている。" },
    { section: "3-12", en: "partition", ja: "分割、仕切り、分割する", ex: "A glass partition separated the rooms.", exJa: "ガラスの仕切りが部屋を区切っていた。" },
    { section: "3-13", en: "carry over", ja: "持ち越す、繰り越す", ex: "Unused days off carry over to next year.", exJa: "使わなかった休みは来年に繰り越される。" }
];