const wordList = [
    // Level 3-01
    { section: "3-01", en: "maneuver", ja: "作戦、策略、巧妙に動かす", ex: "He made a clever maneuver to win.", exJa: "彼は勝つために巧妙な作戦を立てた。" },
    { section: "3-01", en: "outbreak", ja: "(病気・戦争などの)突発、発生", ex: "The outbreak of the flu spread quickly.", exJa: "インフルエンザの突発的発生が急速に広がった。" },
    { section: "3-01", en: "infection", ja: "感染、伝染病", ex: "Wash your hands to prevent infection.", exJa: "感染を防ぐために手を洗いましょう。" },
    { section: "3-01", en: "strategy", ja: "戦略、計画", ex: "We need a new marketing strategy.", exJa: "我々には新しいマーケティング戦略が必要だ。" },
    { section: "3-01", en: "contend", ja: "戦う、主張する", ex: "She had to contend with many difficulties.", exJa: "彼女は多くの困難と戦わなければならなかった。" },
    { section: "3-01", en: "appliance", ja: "器具、家電製品", ex: "Refrigerators are essential kitchen appliances.", exJa: "冷蔵庫は必須の家電製品だ。" },
    { section: "3-01", en: "deploy", ja: "配置する、展開する", ex: "The army was deployed to the border.", exJa: "軍隊が国境に配置された。" },
    { section: "3-01", en: "extract", ja: "抽出する、取り出す", ex: "Scientists extract oil from plants.", exJa: "科学者たちは植物から油を抽出する。" },
    { section: "3-01", en: "scheme", ja: "計画、陰謀", ex: "They hatched a scheme to rob the bank.", exJa: "彼らは銀行を襲う陰謀を企てた。" },
    { section: "3-01", en: "affirm", ja: "断言する、肯定する", ex: "He affirmed his commitment to the project.", exJa: "彼はプロジェクトへのコミットメントを断言した。" },
    { section: "3-01", en: "evaporate", ja: "蒸発する、消え去る", ex: "Water evaporates when heated.", exJa: "水は熱せられると蒸発する。" },
    { section: "3-01", en: "commute", ja: "通勤・通学する", ex: "It takes an hour to commute to work.", exJa: "通勤に1時間かかる。" },
    { section: "3-01", en: "tactic", ja: "戦術、駆け引き", ex: "Their negotiation tactic worked well.", exJa: "彼らの交渉の駆け引きがうまくいった。" },
    { section: "3-01", en: "drift", ja: "漂う、漂流する", ex: "The boat began to drift out to sea.", exJa: "ボートが海へ向かって漂流し始めた。" },
    { section: "3-01", en: "cue", ja: "合図、ヒント", ex: "Wait for my cue before speaking.", exJa: "話す前に私の合図を待て。" },
    { section: "3-01", en: "activate", ja: "作動させる、活性化する", ex: "Press the button to activate the alarm.", exJa: "アラームを作動させるにはボタンを押して。" },
    { section: "3-01", en: "presume", ja: "推定する、思う", ex: "I presume you are tired from the trip.", exJa: "旅行でお疲れのことと推測します。" },
    { section: "3-01", en: "contemplate", ja: "熟考する、じっくり考える", ex: "He contemplated his future career.", exJa: "彼は自分の将来のキャリアについて熟考した。" },
    { section: "3-01", en: "molecule", ja: "分子", ex: "Water is made of molecules.", exJa: "水は分子からできている。" },
    { section: "3-01", en: "stroke", ja: "脳卒中、一撃、なでること", ex: "He suffered a minor stroke last year.", exJa: "彼は昨年軽い脳卒中を患った。" },
    { section: "3-01", en: "stray", ja: "迷い出る、脱線する", ex: "A stray dog wandered into our yard.", exJa: "野良犬が私たちの庭に迷い込んできた。" },
    { section: "3-01", en: "orbit", ja: "軌道、軌道を周回する", ex: "The satellite entered into orbit.", exJa: "衛星が軌道に乗った。" },
    { section: "3-01", en: "rebel", ja: "反逆者、反逆する", ex: "They rebelled against the unfair tax.", exJa: "彼らは不当な税金に対して反逆した。" },
    { section: "3-01", en: "stroll", ja: "ぶらぶら歩く、散歩", ex: "We took a stroll along the beach.", exJa: "私たちは海岸に沿って散歩した。" },
    { section: "3-01", en: "deteriorate", ja: "悪化する", ex: "His health began to deteriorate.", exJa: "彼の健康状態が悪化し始めた。" },
    { section: "3-01", en: "descend", ja: "下る、降りる", ex: "The plane started to descend.", exJa: "飛行機が下降し始めた。" },
    { section: "3-01", en: "chronic", ja: "慢性の", ex: "She suffers from chronic back pain.", exJa: "彼女は慢性的な腰痛に苦しんでいる。" },
    { section: "3-01", en: "inquire", ja: "尋ねる、問い合わせる", ex: "I called to inquire about the schedule.", exJa: "私はスケジュールについて問い合わせるために電話した。" },
    { section: "3-01", en: "radiation", ja: "放射線、放射能", ex: "Exposure to radiation is dangerous.", exJa: "放射線への被曝は危険だ。" },
    { section: "3-01", en: "combat", ja: "戦闘、格闘する", ex: "They are fighting to combat poverty.", exJa: "彼らは貧困と戦うために奮闘している。" },
    { section: "3-01", en: "proclaim", ja: "宣言する、公表する", ex: "The president proclaimed a state of emergency.", exJa: "大統領は非常事態を宣言した。" },
    { section: "3-01", en: "tissue", ja: "(生物の)組織、ティッシュ", ex: "Muscle tissue needs protein to grow.", exJa: "筋肉組織の成長にはタンパク質が必要だ。" },
    { section: "3-01", en: "swell", ja: "膨らむ、増大する", ex: "Her ankle began to swell after the injury.", exJa: "怪我の後、彼女の足首が腫れ始めた。" },
    { section: "3-01", en: "boast", ja: "自慢する", ex: "He loves to boast about his success.", exJa: "彼は自分の成功を自慢するのが好きだ。" },
    { section: "3-01", en: "conceive", ja: "心に抱く、思いつく", ex: "I can't conceive how he did it.", exJa: "彼がそれをどうやったのか私には想像もつかない。" },
    { section: "3-01", en: "stumble", ja: "つまずく、偶然見つける", ex: "I stumbled upon an old diary.", exJa: "私は古い日記を偶然見つけた。" },
    { section: "3-01", en: "influx", ja: "流入", ex: "There was an influx of tourists.", exJa: "観光客の大量流入があった。" },
    { section: "3-01", en: "scar", ja: "傷跡、心の傷", ex: "The burn left a small scar.", exJa: "その火傷は小さな傷跡を残した。" },
    { section: "3-01", en: "retreat", ja: "後退する、引きこもる", ex: "The army was forced to retreat.", exJa: "軍は撤退を余儀なくされた。" },
    { section: "3-01", en: "epidemic", ja: "伝染病の流行", ex: "An epidemic of flu swept the city.", exJa: "インフルエンザの流行が街を席巻した。" },
    { section: "3-01", en: "alternative", ja: "代わりの、選択肢", ex: "Is there an alternative solution?", exJa: "別の解決策はありますか？" },
    { section: "3-01", en: "paralyze", ja: "まひさせる", ex: "The heavy snow paralyzed traffic.", exJa: "大雪が交通をまひさせた。" },
    { section: "3-01", en: "relocate", ja: "移転する、引っ越す", ex: "The company plans to relocate its office.", exJa: "会社はオフィスを移転する予定だ。" },

    // Level 3-02
    { section: "3-02", en: "apprehension", ja: "懸念、不安、逮捕", ex: "She felt a sense of apprehension.", exJa: "彼女は不安感を抱いた。" },
    { section: "3-02", en: "obesity", ja: "肥満", ex: "Childhood obesity is a growing problem.", exJa: "小児肥満は深刻化している問題だ。" },
    { section: "3-02", en: "fatigue", ja: "疲労", ex: "Driving while fatigue is dangerous.", exJa: "疲労状態での運転は危険だ。" },
    { section: "3-02", en: "perpetual", ja: "永続的な、絶え間ない", ex: "They live in perpetual fear.", exJa: "彼らは絶え間ない恐怖の中で暮らしている。" },
    { section: "3-02", en: "sustain", ja: "維持する、支える", ex: "Can the earth sustain more people?", exJa: "地球はさらに多くの人を養い支えることができるか？" },
    { section: "3-02", en: "bewildered", ja: "戸惑った、面食らった", ex: "He looked bewildered by the question.", exJa: "彼はその質問に戸惑っているように見えた。" },
    { section: "3-02", en: "dizzy", ja: "めまいがする", ex: "The high altitude made me dizzy.", exJa: "高地のためにめまいがした。" },
    { section: "3-02", en: "sniff", ja: "くんくん嗅ぐ、鼻をすする", ex: "The dog sniffed at the door.", exJa: "犬がドアのにおいをくんくんとかいだ。" },
    { section: "3-02", en: "sequence", ja: "連続、順序", ex: "Follow the instructions in sequence.", exJa: "指示に従って順番通りに進めてください。" },
    { section: "3-02", en: "successive", ja: "連続した", ex: "It rained for three successive days.", exJa: "3日連続で雨が降った。" },
    { section: "3-02", en: "resent", ja: "憤慨する、恨む", ex: "She resented being treated like a child.", exJa: "彼女は子供扱いされることに憤慨した。" },
    { section: "3-02", en: "empathy", ja: "共感、感情移入", ex: "Good leaders show empathy for others.", exJa: "優れたリーダーは他者への共感を示す。" },
    { section: "3-02", en: "nourish", ja: "栄養を与える、育む", ex: "Breast milk nourishes the baby.", exJa: "母乳が赤ちゃんの栄養を育む。" },
    { section: "3-02", en: "hospitality", ja: "手厚いもてなし、歓待", ex: "Thank you for your warm hospitality.", exJa: "温かいおもてなしをありがとうございます。" },
    { section: "3-02", en: "remedy", ja: "治療法、改善策", ex: "There is no simple remedy for this.", exJa: "これに対する簡単な解決策はない。" },
    { section: "3-02", en: "frail", ja: "虚弱な、壊れやすい", ex: "He is growing old and frail.", exJa: "彼は年老いて体が弱くなってきている。" },
    { section: "3-02", en: "drain", ja: "排出する、疲れ果てさせる", ex: "The long trip drained his energy.", exJa: "長い旅行で彼のエネルギーがすっかり奪われた。" },
    { section: "3-02", en: "fierce", ja: "激しい、凶暴な", ex: "There was fierce competition for the job.", exJa: "その仕事を手に入れるための激しい競争があった。" },
    { section: "3-02", en: "haunt", ja: "(幽霊などが)出没する、つきまとう", ex: "Memories of the accident haunt him.", exJa: "事故の記憶が彼につきまとっている。" },
    { section: "3-02", en: "sympathetic", ja: "同情的な、共感する", ex: "Friends were very sympathetic.", exJa: "友人たちはとても同情だった。" },
    { section: "3-02", en: "persist", ja: "固執する、持続する", ex: "If the symptoms persist, see a doctor.", exJa: "症状が続く場合は医師の診察を受けてください。" },
    { section: "3-02", en: "isolate", ja: "隔離する、孤立させる", ex: "Patients with the virus were isolated.", exJa: "ウイルス患者は隔離された。" },
    { section: "3-02", en: "shrug", ja: "肩をすくめる", ex: "He just shrugged his shoulders.", exJa: "彼はただ肩をすくめた。" },
    { section: "3-02", en: "intervene", ja: "介入する", ex: "Police had to intervene in the fight.", exJa: "警察がその喧嘩に介入せざるを得なかった。" },
    { section: "3-02", en: "retain", ja: "保持する、心にとどめる", ex: "Try to retain what you have learned.", exJa: "学んだことをしっかり心にとどめておきなさい。" },
    { section: "3-02", en: "physician", ja: "医師、内科医", ex: "She consulted a physician about her cough.", exJa: "彼女は咳について医師に相談した。" },
    { section: "3-02", en: "sarcastic", ja: "皮肉な、嫌味な", ex: "He made a sarcastic remark.", exJa: "彼は皮肉な発言をした。" },
    { section: "3-02", en: "diagnose", ja: "診断する", ex: "He was diagnosed with pneumonia.", exJa: "彼は肺炎と診断された。" },
    { section: "3-02", en: "recipient", ja: "受取人", ex: "She was the recipient of the award.", exJa: "彼女はその賞の受賞者だった。" },
    { section: "3-02", en: "provoke", ja: "引き起こす、挑発する", ex: "His remarks provoked an angry response.", exJa: "彼の発言が怒りの反応を引き起こした。" },
    { section: "3-02", en: "withstand", ja: "耐える、抵抗する", ex: "The building can withstand earthquakes.", exJa: "その建物は地震に耐えることができる。" },
    { section: "3-02", en: "gratitude", ja: "感謝", ex: "I expressed my deep gratitude to them.", exJa: "私は彼らに深い感謝の意を表した。" },
    { section: "3-02", en: "humiliate", ja: "恥をかかせる、屈辱を与える", ex: "He felt humiliated by the failure.", exJa: "彼はその失敗で恥をかかされたと感じた。" },
    { section: "3-02", en: "console", ja: "慰める", ex: "Nothing could console her after the loss.", exJa: "その喪失の後、彼女を慰めるものは何もなかった。" },
    { section: "3-02", en: "numb", ja: "麻痺した、感覚のない", ex: "My fingers were numb with cold.", exJa: "寒さで指の感覚がなかった。" },
    { section: "3-02", en: "undergo", ja: "経験する、受ける", ex: "She had to undergo surgery.", exJa: "彼女は手術を受けなければならなかった。" },
    { section: "3-02", en: "prescribe", ja: "処方する、指示する", ex: "The doctor prescribed some medicine.", exJa: "医師が薬を処方してくれた。" },
    { section: "3-02", en: "sewage", ja: "下水、汚水", ex: "The city lacks proper sewage treatment.", exJa: "その都市は適切な下水処理が不足している。" },
    { section: "3-02", en: "transplant", ja: "移植、移植する", ex: "He received a heart transplant.", exJa: "彼は心臓移植を受けた。" },
    { section: "3-02", en: "genetic", ja: "遺伝子の", ex: "It is a rare genetic disorder.", exJa: "それは珍しい遺伝性疾患だ。" },
    { section: "3-02", en: "dismay", ja: "落胆、失望させる", ex: "To my dismay, I missed the train.", exJa: "がっかりしたことに、私は電車に乗り遅れた。" },
    { section: "3-02", en: "immune", ja: "免疫のある、影響を受けない", ex: "Babies are immune to some diseases.", exJa: "赤ちゃんならではの免疫がある病気もある。" },
    { section: "3-02", en: "circulate", ja: "循環する、流通する", ex: "Blood circulates through the body.", exJa: "血液は体内を循環する。" },
    { section: "3-02", en: "sanitary", ja: "衛生的な、清潔な", ex: "Ensure you maintain sanitary conditions.", exJa: "衛生的な環境を保つようにしなさい。" },
    { section: "3-02", en: "durable", ja: "耐久性のある、長持ちする", ex: "This material is very durable.", exJa: "この素材は非常に耐久性がある。" },
    { section: "3-02", en: "terminal", ja: "末期の、終わりの、ターミナル", ex: "He is facing a terminal illness.", exJa: "彼は末期の病気と直面している。" },
    { section: "3-02", en: "perspire", ja: "汗をかく", ex: "I tend to perspire a lot when running.", exJa: "走るときにたくさん汗をかく傾向がある。" },
    { section: "3-02", en: "harass", ja: "嫌がらせをする、悩ませる", ex: "Workers should not be harassed.", exJa: "労働者が嫌がらせを受けてはならない。" },
    { section: "3-02", en: "distress", ja: "苦しみ、悲嘆、悩ませる", ex: "The news caused her great distress.", exJa: "そのニュースは彼女をひどく悲嘆に暮れさせた。" },

    // Level 3-03
    { section: "3-03", en: "treaty", ja: "条約、協定", ex: "The two countries signed a peace treaty.", exJa: "両国は平和条約に署名した。" },
    { section: "3-03", en: "exile", ja: "追放、亡命、追放する", ex: "He lived many years in political exile.", exJa: "彼は長年政治的亡命生活を送った。" },
    { section: "3-03", en: "considerable", ja: "かなりの、相当な", ex: "We spent a considerable amount of money.", exJa: "私たちはかなりの額のお金を費やした。" },
    { section: "3-03", en: "domestic", ja: "国内の、家庭の", ex: "Domestic flights are usually cheaper.", exJa: "国内線はたいていより安い。" },
    { section: "3-03", en: "refugee", ja: "難民", ex: "Thousands of refugees fled the country.", exJa: "何千人もの難民がその国から逃げ出した。" },
    { section: "3-03", en: "sanction", ja: "制裁、認可", ex: "The UN imposed economic sanctions.", exJa: "国連が経済制裁を科した。" },
    { section: "3-03", en: "dispatch", ja: "派遣する、急送する", ex: "They dispatched a team to the site.", exJa: "彼らは現地にチームを派遣した。" },
    { section: "3-03", en: "intake", ja: "摂取量", ex: "Reduce your daily sugar intake.", exJa: "毎日の糖分摂取量を減らしなさい。" },
    { section: "3-03", en: "delegate", ja: "代表団、委任する", ex: "She was sent as a delegate to the summit.", exJa: "彼女はサミットの代表団として派遣された。" },
    { section: "3-03", en: "renew", ja: "更新する、新しくする", ex: "I need to renew my passport.", exJa: "パスポートを更新しなければならない。" },
    { section: "3-03", en: "adore", ja: "大好きである、崇拝する", ex: "She adores playing with her pets.", exJa: "彼女はペットと遊ぶのが大好きだ。" },
    { section: "3-03", en: "spontaneous", ja: "自発的な、自然発生的な", ex: "There was a spontaneous burst of applause.", exJa: "自然発生的な拍手の嵐が起きた。" },
    { section: "3-03", en: "intimate", ja: "親密な、親しい", ex: "We are on intimate terms.", exJa: "私たちは親密な間柄だ。" },
    { section: "3-03", en: "gulp", ja: "ゴクゴク飲む、のみこむ", ex: "He gulped down his cold drink.", exJa: "彼は冷たい飲み物をゴクゴクと飲み干した。" },
    { section: "3-03", en: "skeptical", ja: "懐疑的な、疑わしい", ex: "I am skeptical about his promises.", exJa: "私は彼の約束について懐疑的だ。" },
    { section: "3-03", en: "dubious", ja: "怪しい、疑わしい", ex: "His explanation seemed rather dubious.", exJa: "彼の説明はかなり怪しく思えた。" },
    { section: "3-03", en: "reunion", ja: "再会、同窓会", ex: "We had a family reunion last weekend.", exJa: "先週末、家族の集まりがあった。" },
    { section: "3-03", en: "revive", ja: "生き返らせる、復活させる", ex: "The company tried to revive sales.", exJa: "その会社は売上を回復させようとした。" },
    { section: "3-03", en: "resilience", ja: "回復力、立ち直る力", ex: "Children show remarkable resilience.", exJa: "子供たちは驚くべき回復力を見せる。" },
    { section: "3-03", en: "resume", ja: "再開する、取り戻す", ex: "Talks will resume tomorrow morning.", exJa: "会談は明日午前に再開される。" },
    { section: "3-03", en: "absolutely", ja: "絶対に、完全に", ex: "You are absolutely right.", exJa: "君の言うことは完全に正しい。" },
    { section: "3-03", en: "retrieve", ja: "回収する、取り戻す", ex: "He dove into the pool to retrieve his keys.", exJa: "彼は鍵を取り戻すためにプールに飛び込んだ。" },
    { section: "3-03", en: "decay", ja: "腐敗、衰退、腐る", ex: "Sugar causes tooth decay.", exJa: "砂糖は虫歯（歯の腐敗）の原因になる。" },
    { section: "3-03", en: "custody", ja: "保管、拘留、保護", ex: "The suspect is now in police custody.", exJa: "容疑者は現在警察の拘留下にある。" },
    { section: "3-03", en: "squeeze", ja: "搾る、締めつける", ex: "Squeeze some lemon juice over the fish.", exJa: "魚にレモンの汁を絞りかけて。" },
    { section: "3-03", en: "sober", ja: "しらふの、まじめな", ex: "He was completely sober when driving.", exJa: "彼は運転中、完全にしらふだった。" },
    { section: "3-03", en: "divorce", ja: "離婚、離婚する", ex: "They decided to get a divorce.", exJa: "彼らは離婚することを決めた。" },
    { section: "3-03", en: "edible", ja: "食べられる、食用の", ex: "Are these wild berries edible?", exJa: "この野生のベリーは食べられますか？" },
    { section: "3-03", en: "inevitable", ja: "避けられない、必然的な", ex: "Change is an inevitable part of life.", exJa: "変化は人生の避けて通れない一部だ。" },
    { section: "3-03", en: "solitude", ja: "孤独、ひとりぼっち", ex: "He enjoys moments of peace and solitude.", exJa: "彼は平和で静かな孤独の時間を楽しんでいる。" },
    { section: "3-03", en: "regain", ja: "取り戻す、回復する", ex: "She managed to regain her composure.", exJa: "彼女は何とか落ち着きを取り戻した。" },
    { section: "3-03", en: "reassure", ja: "安心させる", ex: "I tried to reassure her that everything was fine.", exJa: "すべて大丈夫だと彼女を安心させようとした。" },
    { section: "3-03", en: "feast", ja: "ごちそう、祝宴", ex: "A grand feast was prepared for the guests.", exJa: "ゲストのために盛大なごちそうが用意された。" },
    { section: "3-03", en: "ambiguous", ja: "あいまいな、多義的な", ex: "His answer was rather ambiguous.", exJa: "彼の答えはかなりあいまいだった。" },
    { section: "3-03", en: "ally", ja: "同盟国、協力者", ex: "They have been close allies for years.", exJa: "彼らは長年親密な同盟国だ。" },
    { section: "3-03", en: "offspring", ja: "子孫、子", ex: "Birds feed their offspring in the nest.", exJa: "鳥は巣の中で子に餌を与える。" },
    { section: "3-03", en: "confidential", ja: "機密の、秘密の", ex: "This information is strictly confidential.", exJa: "この情報は厳に機密扱いである。" },
    { section: "3-03", en: "diplomat", ja: "外交官", ex: "He worked as a senior diplomat.", exJa: "彼は上級外交官として働いた。" },
    { section: "3-03", en: "sibling", ja: "きょうだい", ex: "I have two siblings, a brother and a sister.", exJa: "私には兄と姉（きょうだい）が2人いる。" },
    { section: "3-03", en: "cherish", ja: "大切にする、胸に抱く", ex: "I will always cherish those memories.", exJa: "私はその思い出をいつまでも大切にする。" },
    { section: "3-03", en: "expire", ja: "期限が切れる、満期になる", ex: "My driver's license expires next month.", exJa: "私の運転免許証は来月期限が切れる。" },
    { section: "3-03", en: "renovate", ja: "改装する、リフォームする", ex: "They renovated their old kitchen.", exJa: "彼らは古いキッチンをリフォームした。" },
    { section: "3-03", en: "conclusive", ja: "決定的な、確証的な", ex: "Police found no conclusive evidence.", exJa: "警察は決定的な証拠を見つけられなかった。" },
    { section: "3-03", en: "thorough", ja: "徹底的な、完全な", ex: "We need a thorough investigation.", exJa: "我々には徹底的な調査が必要だ。" },
    { section: "3-03", en: "respectively", ja: "それぞれ、めいめいに", ex: "Tom and Mary are 10 and 12 respectively.", exJa: "トムとメアリーはそれぞれ10歳と12歳だ。" },
    { section: "3-03", en: "infant", ja: "幼児、乳児", ex: "The infant fell asleep in her arms.", exJa: "乳児は彼女の腕の中で眠りについた。" },
    { section: "3-03", en: "orphan", ja: "孤児", ex: "The charity helps orphans around the world.", exJa: "その慈善団体は世界中の孤児を支援している。" },

    // Level 3-04
    { section: "3-04", en: "hazard", ja: "危険、危険要素", ex: "Smoking is a health hazard.", exJa: "喫煙は健康上の危険要因だ。" },
    { section: "3-04", en: "surveillance", ja: "監視、見張り", ex: "The building is under 24-hour surveillance.", exJa: "その建物は24時間監視下にある。" },
    { section: "3-04", en: "closure", ja: "閉鎖、終結", ex: "The road closure caused heavy traffic.", exJa: "道路の閉鎖で大渋滞が起きた。" },
    { section: "3-04", en: "graze", ja: "放牧する、かすめる", ex: "Cows graze in the green meadow.", exJa: "牛が緑の牧草地で草を食んでいる。" },
    { section: "3-04", en: "dense", ja: "密集した、濃い", ex: "A dense fog covered the city.", exJa: "濃い霧が街を覆った。" },
    { section: "3-04", en: "ultimately", ja: "結局、最後に", ex: "Hard work will ultimately pay off.", exJa: "努力は最終的に報われるだろう。" },
    { section: "3-04", en: "application", ja: "応用、申請、申し込み", ex: "Submit your application by Friday.", exJa: "金曜日までに申請書を提出してください。" },
    { section: "3-04", en: "menace", ja: "脅威、厄介なもの", ex: "Pollution is a menace to society.", exJa: "汚染は社会に対する脅威だ。" },
    { section: "3-04", en: "thrive", ja: "繁栄する、成長する", ex: "Plants thrive in sunlight and water.", exJa: "植物は日光と水ですくすく育つ。" },
    { section: "3-04", en: "herd", ja: "（牛などの）群れ", ex: "A herd of elephants crossed the river.", exJa: "ゾンの群れが川を渡った。" },
    { section: "3-04", en: "discipline", ja: "規律、訓練、しつけ", ex: "School requires strict discipline.", exJa: "学校には厳しい規律が求められる。" },
    { section: "3-04", en: "crucial", ja: "重大な、決定的な", ex: "This decision is crucial for our future.", exJa: "この決定は私たちの将来にとって極めて重大だ。" },
    { section: "3-04", en: "flammable", ja: "燃えやすい、可燃性の", ex: "Keep away from flammable materials.", exJa: "可燃性の素材に近づかないようにしなさい。" },
    { section: "3-04", en: "comprehend", ja: "理解する", ex: "I couldn't comprehend his strange behavior.", exJa: "彼の奇妙な行動が理解できなかった。" },
    { section: "3-04", en: "nurture", ja: "育む、養育する", ex: "Parents nurture their children with love.", exJa: "親は愛を持って子供を育む。" },
    { section: "3-04", en: "grasp", ja: "把握する、しっかり握る", ex: "I failed to grasp the main point.", exJa: "私は要点を把握し損ねた。" },
    { section: "3-04", en: "foster", ja: "育成する、促進する", ex: "The school fosters creativity in students.", exJa: "その学校は生徒の創造性を育成する。" },
    { section: "3-04", en: "contaminate", ja: "汚染する", ex: "Chemicals contaminated the water supply.", exJa: "化学物質が水道水を汚染した。" },
    { section: "3-04", en: "consequence", ja: "結果、重大さ", ex: "You must face the consequences.", exJa: "あなたは結果に直面しなければならない。" },
    { section: "3-04", en: "stem", ja: "由来する、茎", ex: "His success stems from hard work.", exJa: "彼の成功は猛勉強に由来している。" },
    { section: "3-04", en: "tuition", ja: "授業料", ex: "University tuition has increased again.", exJa: "大学の授業料がまた値上がりした。" },
    { section: "3-04", en: "wither", ja: "しおれる、衰える", ex: "The flowers withered in the hot sun.", exJa: "暑い太陽の下で花がしおれてしまった。" },
    { section: "3-04", en: "fatal", ja: "致命的な、取り返しのつかない", ex: "It was a fatal mistake.", exJa: "それは致命的な間違いだった。" },
    { section: "3-04", en: "familiarize", ja: "慣れさせる、熟知させる", ex: "Familiarize yourself with the rules.", exJa: "ルールをよく自分で熟知しておきなさい。" },
    { section: "3-04", en: "drench", ja: "びしょ濡れにする", ex: "The sudden rain drenched us.", exJa: "突然の雨が私たちをびしょ濡れにした。" },
    { section: "3-04", en: "moisture", ja: "湿気、水分", ex: "Plants need moisture to grow.", exJa: "植物の成長には水分が必要だ。" },
    { section: "3-04", en: "litter", ja: "ごみ、散らかす", ex: "Do not litter on the streets.", exJa: "道路にごみを散らかしてはいけない。" },
    { section: "3-04", en: "exterminate", ja: "根絶する、絶滅させる", ex: "Efforts were made to exterminate pests.", exJa: "害虫を根絶する努力がなされた。" },
    { section: "3-04", en: "gloomy", ja: "憂鬱な、暗い", ex: "He had a gloomy expression on his face.", exJa: "彼の顔には憂鬱な表情が浮かんでいた。" },
    { section: "3-04", en: "landfill", ja: "埋立地、ごみ処分場", ex: "Much of our waste goes to the landfill.", exJa: "私たちのゴミの多くは埋立地行きになる。" },
    { section: "3-04", en: "impair", ja: "損なう、弱める", ex: "Lack of sleep impairs your judgment.", exJa: "睡眠不足は判断力を損なう。" },
    { section: "3-04", en: "rigorous", ja: "厳格な、過酷な", ex: "They underwent rigorous training.", exJa: "彼らは過酷な訓練を受けた。" },
    { section: "3-04", en: "bark", ja: "樹皮、犬などの吠え声", ex: "The dog's bark echoed in the night.", exJa: "夜の中に犬の吠え声が響いた。" },
    { section: "3-04", en: "inflict", ja: "（苦痛などを）与える", ex: "The storm inflicted heavy damage.", exJa: "嵐が甚大な被害を与えた。" },
    { section: "3-04", en: "rigid", ja: "厳格な、硬直した", ex: "The company has rigid rules.", exJa: "その会社には厳格な規則がある。" },
    { section: "3-04", en: "diversity", ja: "多様性", ex: "We value cultural diversity.", exJa: "私たちは文化の多様性を尊重する。" },
    { section: "3-04", en: "tame", ja: "飼いならす、従順な", ex: "It is hard to tame a wild animal.", exJa: "野生動物を飼いならすのは難しい。" },
    { section: "3-04", en: "harsh", ja: "過酷な、厳しい", ex: "They survived the harsh winter.", exJa: "彼らは厳しい冬を生き延びた。" },
    { section: "3-04", en: "coral", ja: "サンゴ", ex: "The sea is home to colorful coral reefs.", exJa: "その海には色鮮やかなサンゴ礁がある。" },
    { section: "3-04", en: "hail", ja: "ひょう、歓迎する", ex: "The crowd hailed the champion.", exJa: "群衆はチャンピオンを歓迎した。" },
    { section: "3-04", en: "penetrate", ja: "貫通する、浸透する", ex: "Light cannot penetrate deep water.", exJa: "光は深い水の中まで届かない（浸透しない）。" },
    { section: "3-04", en: "dispose", ja: "処分する、処理する", ex: "How should I dispose of this waste?", exJa: "このゴミはどう処分すればよいですか？" },

    // Level 3-05
    { section: "3-05", en: "momentum", ja: "勢い、弾み", ex: "The campaign is gaining momentum.", exJa: "キャンペーンは勢いを増している。" },
    { section: "3-05", en: "inflate", ja: "膨らませる、インフレさせる", ex: "He inflated the bicycle tires.", exJa: "彼は自転車のタイヤに空気を膨らませた。" },
    { section: "3-05", en: "variable", ja: "変数、変動しやすいもの", ex: "Weather is a key variable.", exJa: "天候は重要な変動要素だ。" },
    { section: "3-05", en: "paradox", ja: "逆説、パラドックス", ex: "It sounds like a paradox, but it's true.", exJa: "逆説に聞こえるが、それは本当だ。" },
    { section: "3-05", en: "shareholder", ja: "株主", ex: "Shareholders approved the merger.", exJa: "株主が合併を承認した。" },
    { section: "3-05", en: "objection", ja: "異議、反対", ex: "Does anyone have an objection?", exJa: "何か異議のある人はいますか？" },
    { section: "3-05", en: "allege", ja: "（証拠なく）主張する、申し立てる", ex: "He is alleged to have stolen the car.", exJa: "彼は車を盗んだと主張（申し立て）されている。" },
    { section: "3-05", en: "workforce", ja: "労働力、全従業員", ex: "The company has a skilled workforce.", exJa: "その会社には熟練した労働力（従業員）がいる。" },
    { section: "3-05", en: "parallel", ja: "平行な、類似の、匹敵するもの", ex: "The two roads run parallel.", exJa: "その2つの道路は平行に走っている。" },
    { section: "3-05", en: "monopoly", ja: "独占、独占企業", ex: "The company holds a market monopoly.", exJa: "その会社は市場を独占している。" },
    { section: "3-05", en: "governance", ja: "統治、管理、ガバナンス", ex: "Good corporate governance is essential.", exJa: "優れたコーポレートガバナンス（企業統治）が不可欠だ。" },
    { section: "3-05", en: "incentive", ja: "動機、インセンティブ、報奨金", ex: "Sales staff receive financial incentives.", exJa: "販売スタッフには金銭的インセンティブが支給される。" },
    { section: "3-05", en: "advocate", ja: "提唱する、支持者", ex: "She advocates for environmental protection.", exJa: "彼女は環境保護を提唱している。" },
    { section: "3-05", en: "synthetic", ja: "合成の、人工の", ex: "This jacket is made of synthetic fibers.", exJa: "このジャケットは合成繊維でできている。" },
    { section: "3-05", en: "impose", ja: "課す、押し付ける", ex: "The government imposed a new tax.", exJa: "政府が新しい税金を課した。" },
    { section: "3-05", en: "compulsory", ja: "強制的な、義務的な", ex: "English is a compulsory subject.", exJa: "英語は必修（義務的）科目だ。" },
    { section: "3-05", en: "unanimously", ja: "満場一致で", ex: "The proposal was passed unanimously.", exJa: "その提案は満場一致で可決された。" },
    { section: "3-05", en: "mandatory", ja: "必須の、義務的な", ex: "Attendance at the meeting is mandatory.", exJa: "ミーティングへの出席は必須だ。" },
    { section: "3-05", en: "restructure", ja: "再構築する、リストラする", ex: "The firm decided to restructure its debt.", exJa: "その会社は借入金の再構築（リストラ）を決定した。" },
    { section: "3-05", en: "merge", ja: "合併する、融合する", ex: "The two banks agreed to merge.", exJa: "2つの銀行が合併することに合意した。" },
    { section: "3-05", en: "executive", ja: "重役、幹部、実行の", ex: "He is a senior corporate executive.", exJa: "彼は企業の最高幹部だ。" },
    { section: "3-05", en: "dispute", ja: "紛争、議論、異議を唱える", ex: "They are in dispute over land ownership.", exJa: "彼らは土地の所有権をめぐって紛争中だ。" },
    { section: "3-05", en: "tender", ja: "入札、優しい、差し出す", ex: "The company submitted a tender.", exJa: "その会社は入札書類を提出した。" },
    { section: "3-05", en: "receptive", ja: "受容的な、快く受け入れる", ex: "She was receptive to new ideas.", exJa: "彼女は新しいアイデアを快く受け入れた。" },
    { section: "3-05", en: "drastic", ja: "徹底的な、思い切った", ex: "We need drastic measures.", exJa: "我々には思い切った措置が必要だ。" },
    { section: "3-05", en: "acknowledge", ja: "認める、承認する", ex: "He acknowledged his mistake.", exJa: "彼は自分の間違いを認めた。" },
    { section: "3-05", en: "bounce", ja: "跳ね返る、弾む", ex: "The ball bounced off the wall.", exJa: "ボールが壁に当たって跳ね返った。" },
    { section: "3-05", en: "friction", ja: "摩擦、不和", ex: "There is friction between the departments.", exJa: "部署間に摩擦（不和）が生じている。" },
    { section: "3-05", en: "massive", ja: "大規模な、巨大な", ex: "A massive earthquake hit the region.", exJa: "巨大な地震がその地域を襲った。" },
    { section: "3-05", en: "transaction", ja: "取引、業務", ex: "Online transactions are safe.", exJa: "オンライン取引は安全だ。" },
    { section: "3-05", en: "compress", ja: "圧縮する、要約する", ex: "You can compress large files.", exJa: "大きなファイルを圧縮することができます。" },
    { section: "3-05", en: "evade", ja: "逃れる、回避する", ex: "He tried to evade paying taxes.", exJa: "彼は脱税（税金を支払うことからの逃避）を企てた。" },
    { section: "3-05", en: "affiliate", ja: "提携する、加入する、関連会社", ex: "The clinic is affiliated with the hospital.", exJa: "そのクリニックはその病院と提携している。" },
    { section: "3-05", en: "subordinate", ja: "下位の、部下", ex: "He treats his subordinates well.", exJa: "彼は部下たちを大切に扱う。" },
    { section: "3-05", en: "obligation", ja: "義務、責任", ex: "I have no legal obligation to answer.", exJa: "私には答える法的義務はない。" },
    { section: "3-05", en: "depression", ja: "不況、憂鬱、意気消沈", ex: "The country fell into a deep depression.", exJa: "その国は深刻な不況に陥った。" },
    { section: "3-05", en: "concede", ja: "認める、譲歩する", ex: "He conceded defeat in the election.", exJa: "彼は選挙での敗北を認めた。" },
    { section: "3-05", en: "grant", ja: "交付する、許可する、補助金", ex: "The council granted permission.", exJa: "評議会が許可を交付した。" },
    { section: "3-05", en: "uphold", ja: "支持する、維持する", ex: "We must uphold the law.", exJa: "私たちは法律を支持し守らなければならない。" },
    { section: "3-05", en: "administer", ja: "管理する、投与する", ex: "Doctors administer medicine to patients.", exJa: "医師が患者に薬を投与する。" },
    { section: "3-05", en: "multinational", ja: "多国籍の", ex: "He works for a multinational corporation.", exJa: "彼は多国籍企業で働いている。" },
    { section: "3-05", en: "convert", ja: "転換する、変える", ex: "Convert dollars into yen.", exJa: "ドルを円に換える。" },
    { section: "3-05", en: "deficit", ja: "赤字、不足", ex: "The company ran a trade deficit.", exJa: "その会社は貿易赤字を出した。" },
    { section: "3-05", en: "transparent", ja: "透明な、わかりやすい", ex: "Glass is a transparent material.", exJa: "ガラスは透明な素材だ。" },
    { section: "3-05", en: "deposit", ja: "預金、預ける、頭金", ex: "I need to deposit money in the bank.", exJa: "銀行にお金を預けなければならない。" },
    { section: "3-05", en: "sphere", ja: "球体、範囲、領域", ex: "The earth is not a perfect sphere.", exJa: "地球は完全な球体ではない。" },
    { section: "3-05", en: "budget", ja: "予算、予算案", ex: "We are working on a tight budget.", exJa: "私たちは厳しい予算の中で作業している。" },
    { section: "3-05", en: "controversial", ja: "議論の余地がある、物議を醸す", ex: "It was a controversial political issue.", exJa: "それは物議を醸す政治問題だった。" },
    { section: "3-05", en: "recession", ja: "景気後退、不景気", ex: "The economy is sliding into a recession.", exJa: "経済が景気後退に突入しつつある。" },
    { section: "3-05", en: "bankrupt", ja: "破産した、倒産した", ex: "The airline went bankrupt.", exJa: "その航空会社は倒産した。" },

    // Level 3-06
    { section: "3-06", en: "distract", ja: "（気を）散らす、紛らわす", ex: "Don't distract me while I'm working.", exJa: "仕事中だから気を散らさないでくれ。" },
    { section: "3-06", en: "prosecute", ja: "起訴する、告発する", ex: "The state will prosecute shoplifters.", exJa: "国は万引き犯を起訴する方針だ。" },
    { section: "3-06", en: "modernize", ja: "近代化する", ex: "They plan to modernize the factory.", exJa: "彼らは工場を近代化する計画だ。" },
    { section: "3-06", en: "preconception", ja: "先入観、偏見", ex: "Try to drop any preconceptions.", exJa: "先入観は一切捨てるようにしなさい。" },
    { section: "3-06", en: "masterpiece", ja: "傑作、名作", ex: "This painting is his masterpiece.", exJa: "この絵画は彼の傑作だ。" },
    { section: "3-06", en: "shove", ja: "ぐっと押す、押しやる", ex: "He gave the door a hard shove.", exJa: "彼はドアをぐっと強く押した。" },
    { section: "3-06", en: "eruption", ja: "噴火、勃発", ex: "The volcanic eruption caused chaos.", exJa: "火山の大噴火が大混乱を引き起こした。" },
    { section: "3-06", en: "evacuate", ja: "避難する、退去する", ex: "Residents were told to evacuate immediately.", exJa: "住民に即座に避難するよう指示が出された。" },
    { section: "3-06", en: "quote", ja: "引用する、引き合いに出す", ex: "He quoted a line from Shakespeare.", exJa: "彼はシェイクスピアのセリフを引用した。" },
    { section: "3-06", en: "cast", ja: "投げる、配役する、配役", ex: "Cast your vote in the box.", exJa: "投票箱に票を投じてください。" },
    { section: "3-06", en: "dictate", ja: "書き取らせる、指図する、決定する", ex: "Don't dictate to me what to do.", exJa: "私に何をすべきか指図しないでくれ。" },
    { section: "3-06", en: "uproar", ja: "大騒ぎ、騒動", ex: "The announcement caused an uproar.", exJa: "その発表は大騒動を引き起こした。" },
    { section: "3-06", en: "simplify", ja: "簡素化する、単純にする", ex: "Try to simplify your explanation.", exJa: "説明をわかりやすく（簡素に）するようにしなさい。" },
    { section: "3-06", en: "mess", ja: "散らかった状態、混乱、困ったこと", ex: "Clean up this messy room.", exJa: "この散らかった部屋を片付けなさい。" },
    { section: "3-06", en: "facilitate", ja: "促進する、容易にする", ex: "Technology facilitates communication.", exJa: "テクノロジーはコミュニケーションを容易にする。" },
    { section: "3-06", en: "audible", ja: "聞き取れる、聞こえる", ex: "Her voice was barely audible.", exJa: "彼女の声はかろうじて聞き取れる程度だった。" },
    { section: "3-06", en: "overlook", ja: "見落とす、見渡す、大目に見る", ex: "I think you overlooked a typo.", exJa: "君は誤字を見落としていると思うよ。" },
    { section: "3-06", en: "plead", ja: "弁護する、懇願する", ex: "He pleaded for mercy.", exJa: "彼は慈悲を乞うて懇願した。" },
    { section: "3-06", en: "cite", ja: "引用する、引き合いに出す", ex: "She cited several examples.", exJa: "彼女はいくつかの例を引き合いに出した。" },
    { section: "3-06", en: "disrupt", ja: "混乱させる、中断させる", ex: "The strike will disrupt train services.", exJa: "ストライキによって電車の運行が中断（混乱）されるだろう。" },
    { section: "3-06", en: "glimpse", ja: "ちらりと見ること、一瞥する", ex: "I caught a glimpse of a celebrity.", exJa: "私は有名人をちらりと見かけた。" },
    { section: "3-06", en: "define", ja: "定義する、明確にする", ex: "How do you define success?", exJa: "あなたにとって成功とはどのように定義されますか？" },
    { section: "3-06", en: "literate", ja: "読み書きができる、教養のある", ex: "Most adults here are literate.", exJa: "ここの大半の成人は読み書きができる。" },
    { section: "3-06", en: "drought", ja: "干ばつ、渇水", ex: "The crops died in the severe drought.", exJa: "農作物が深刻な干ばつで枯れてしまった。" },
    { section: "3-06", en: "tumble", ja: "転がる、暴落する、転落", ex: "Stock prices tumbled today.", exJa: "今日の株価が暴落した。" },
    { section: "3-06", en: "wreck", ja: "難破船、残骸、破壊する", ex: "The storm left a wreck of the ship.", exJa: "嵐はその船の残骸を残した。" },
    { section: "3-06", en: "sculpture", ja: "彫刻、彫刻作品", ex: "He carved a beautiful wooden sculpture.", exJa: "彼は美しい木の彫刻を彫った。" },
    { section: "3-06", en: "modify", ja: "修正する、変更する", ex: "We need to modify the design.", exJa: "私たちはデザインを修正する必要がある。" },
    { section: "3-06", en: "innovation", ja: "革新、技術革新", ex: "Technological innovation drives growth.", exJa: "技術革新が成長を牽引する。" },
    { section: "3-06", en: "chaos", ja: "大混乱、カオス", ex: "The power outage caused total chaos.", exJa: "停電が完全な大混乱を引き起こした。" },
    { section: "3-06", en: "compliment", ja: "お世辞、ほめ言葉、ほめる", ex: "Thank you for the nice compliment.", exJa: "素敵なほめ言葉をありがとう。" },
    { section: "3-06", en: "tangle", ja: "からまる、もつれ", ex: "My hair got in a tangle.", exJa: "私の髪がもつれてしまった。" },
    { section: "3-06", en: "radical", ja: "根本的な、急進的な", ex: "The party proposed radical reforms.", exJa: "その政党は根本的な改革を提案した。" },
    { section: "3-06", en: "racism", ja: "人種差別", ex: "Society must fight against racism.", exJa: "社会は人種差別と戦わなければならない。" },
    { section: "3-06", en: "oppress", ja: "圧迫する、しいたげる", ex: "Tyrants oppress their people.", exJa: "専制君主は人々をしいたげる。" },
    { section: "3-06", en: "prejudice", ja: "偏見、成見", ex: "We must overcome racial prejudice.", exJa: "私たちは人種的偏見を克服しなければならない。" },
    { section: "3-06", en: "enhance", ja: "高める、強化する", ex: "Good lighting enhances the room's look.", exJa: "良い照明が部屋の見た目を一段と引き立てる（高める）。" },
    { section: "3-06", en: "abstract", ja: "抽象的な、要約、抽象概念", ex: "His theory is too abstract.", exJa: "彼の理論は抽象的すぎる。" },
    { section: "3-06", en: "conviction", ja: "確信、有罪判決", ex: "She spoke with deep conviction.", exJa: "彼女は深い確信を持って語った。" },
    { section: "3-06", en: "disorder", ja: "無秩序、不調、疾患", ex: "He suffers from a sleep disorder.", exJa: "彼は睡眠障害に悩まされている。" },
    { section: "3-06", en: "odor", ja: "におい、香り", ex: "A strange odor came from the kitchen.", exJa: "キッチンから変なにおいがしてきた。" },
    { section: "3-06", en: "devastate", ja: "荒廃させる、打ちのめす", ex: "The flood devastated the town.", exJa: "洪水がその町を荒廃させた。" },
    { section: "3-06", en: "casualty", ja: "死傷者、被害者", ex: "There were heavy casualties in the crash.", exJa: "その墜落事故で多くの死傷者が出た。" },
    { section: "3-06", en: "scatter", ja: "まき散らす、分散させる", ex: "The wind scattered the leaves.", exJa: "風が葉をまき散らした。" },
    { section: "3-06", en: "riot", ja: "暴動、暴動を起こす", ex: "Riots broke out across the city.", exJa: "市内で暴動が勃発した。" },
    { section: "3-06", en: "verbal", ja: "言葉の、口頭の", ex: "They had a verbal agreement.", exJa: "彼らは口頭での合意（約束）を交わした。" },

    // Level 3-07
    { section: "3-07", en: "overlap", ja: "重複する、重なり合う", ex: "Our schedules overlap next week.", exJa: "来週、私たちのスケジュールが重なっている。" },
    { section: "3-07", en: "simultaneously", ja: "同時に", ex: "The two events happened simultaneously.", exJa: "その2つの出来事は同時に起きた。" },
    { section: "3-07", en: "exempt", ja: "免除された、免除する", ex: "Students are exempt from this fee.", exJa: "学生はこの料金が免除される。" },
    { section: "3-07", en: "ritual", ja: "儀式、慣習", ex: "Morning coffee is part of my daily ritual.", exJa: "朝のコーヒーは私の毎日の儀式（日課）の一部だ。" },
    { section: "3-07", en: "subsidy", ja: "補助金、助成金", ex: "The farm receives a government subsidy.", exJa: "その農場は政府から補助金を受けている。" },
    { section: "3-07", en: "feasible", ja: "実現可能な", ex: "Is your plan practically feasible?", exJa: "君の計画は実質的に実現可能かい？" },
    { section: "3-07", en: "grave", ja: "重大な、深刻な、墓", ex: "The situation is extremely grave.", exJa: "状況は極めて深刻だ。" },
    { section: "3-07", en: "toll", ja: "通行料、犠牲、損害", ex: "The highway toll increased.", exJa: "高速道路の通行料が値上がりした。" },
    { section: "3-07", en: "procession", ja: "行列、列", ex: "A funeral procession moved slowly down the street.", exJa: "葬列が通りをゆっくりと進んでいった。" },
    { section: "3-07", en: "deduct", ja: "差し引く、控除する", ex: "Tax will be deducted from your salary.", exJa: "給料から税金が差し引かれます。" },
    { section: "3-07", en: "inherit", ja: "受け継ぐ、相続する", ex: "She inherited a house from her uncle.", exJa: "彼女は叔父から家を相続した。" },
    { section: "3-07", en: "overdue", ja: "期限が過ぎた、遅れている", ex: "This library book is overdue.", exJa: "この図書館の本は返却期限が過ぎている。" },
    { section: "3-07", en: "collective", ja: "集団の、共同の", ex: "It was a collective decision.", exJa: "それは集団による決定だった。" },
    { section: "3-07", en: "widespread", ja: "広範囲にわたる、普及した", ex: "There is widespread support for the policy.", exJa: "その政策には広範囲にわたる支持が集まっている。" },
    { section: "3-07", en: "mourn", ja: "悼む、嘆く", ex: "The nation mourned the leader's death.", exJa: "国民はそのリーダーの死を悼んだ。" },
    { section: "3-07", en: "agitate", ja: "扇動する、動揺させる", ex: "Activists agitated for better wages.", exJa: "活動家たちがより良い賃金を求めて扇動（運動）した。" },
    { section: "3-07", en: "stability", ja: "安定、安定性", ex: "Economic stability is vital.", exJa: "経済の安定が極めて重要だ。" },
    { section: "3-07", en: "prosper", ja: "繁栄する", ex: "Businesses need peace to prosper.", exJa: "ビジネスが繁栄するには平和が必要だ。" },
    { section: "3-07", en: "adolescent", ja: "思春期の若者、思春期の", ex: "He works with troubled adolescents.", exJa: "彼は問題を抱えた思春期の若者たちを支援している。" },
    { section: "3-07", en: "commemorate", ja: "記念する、祝う", ex: "We commemorate our anniversary today.", exJa: "私たちは今日、記念日を祝う。" },
    { section: "3-07", en: "gender", ja: "性別", ex: "Discrimination based on gender is illegal.", exJa: "性別に基づく差別は違法だ。" },
    { section: "3-07", en: "execute", ja: "実行する、処刑する", ex: "They executed the plan successfully.", exJa: "彼らは計画を首尾よく実行した。" },
    { section: "3-07", en: "compensation", ja: "報酬、補償金", ex: "He demanded compensation for the injury.", exJa: "彼は怪我に対する補償金を要求した。" },
    { section: "3-07", en: "implement", ja: "実行する、実装する、道具", ex: "The school will implement a new rule.", exJa: "学校側は新しい規則を実行する予定だ。" },
    { section: "3-07", en: "synchronize", ja: "同調させる、同期する", ex: "Synchronize your watches.", exJa: "時計の時間を合わせなさい（同期させなさい）。" },
    { section: "3-07", en: "charitable", ja: "慈善の、慈悲深い", ex: "She made a charitable donation.", exJa: "彼女は慈善寄付を行った。" },
    { section: "3-07", en: "asset", ja: "資産、財産、長所", ex: "Experience is a valuable asset.", exJa: "経験は貴重な財産だ。" },
    { section: "3-07", en: "activist", ja: "活動家", ex: "Political activists gathered in the square.", exJa: "政治活動家たちが広場に集まった。" },
    { section: "3-07", en: "premature", ja: "時期尚早の、早すぎる", ex: "It is premature to judge the results.", exJa: "結果を判断するのは時期尚早だ。" },
    { section: "3-07", en: "donate", ja: "寄付する、提供する", ex: "He donated money to charity.", exJa: "彼は慈善団体にお金を寄付した。" },
    { section: "3-07", en: "doom", ja: "運命づける、破滅、不運", ex: "Their project was doomed to fail.", exJa: "彼らのプロジェクトは失敗する運命にあった。" },
    { section: "3-07", en: "assemble", ja: "組み立てる、集まる", ex: "Workers assemble cars in the factory.", exJa: "作業員たちが工場で車を組み立てる。" },
    { section: "3-07", en: "mortal", ja: "死すべき運命の、致命的な", ex: "All human beings are mortal.", exJa: "人間はみな死すべき運命にある。" },
    { section: "3-07", en: "commence", ja: "始まる、開始する", ex: "The ceremony will commence at noon.", exJa: "式典は正午に開始される。" },
    { section: "3-07", en: "privilege", ja: "特権、特典", ex: "Education should be a right, not a privilege.", exJa: "教育は特権ではなく権利であるべきだ。" },
    { section: "3-07", en: "span", ja: "期間、架け渡す、及ぶ", ex: "His career spanned 40 years.", exJa: "彼のキャリアは40年に及んだ。" },
    { section: "3-07", en: "immortal", ja: "不滅の、不死の", ex: "His music achieved immortal fame.", exJa: "彼の音楽は不滅の栄声を獲得した。" },
    { section: "3-07", en: "invaluable", ja: "非常に価値のある、かけがえのない", ex: "Thank you for your invaluable advice.", exJa: "かけがえのないアドバイスをありがとう。" },
    { section: "3-07", en: "contemporary", ja: "現代の、同時代の", ex: "She is a contemporary artist.", exJa: "彼女は現代のアーティストだ。" },
    { section: "3-07", en: "prolong", ja: "長引かせる、延長する", ex: "Treatment can prolong life.", exJa: "治療によって命を長らえさせることができる。" },
    { section: "3-07", en: "forthcoming", ja: "来たるべき、入手可能な", ex: "I look forward to the forthcoming movie.", exJa: "今度公開される映画が楽しみだ。" },
    { section: "3-07", en: "subsequent", ja: "その後の、引き続いての", ex: "Subsequent events proved him right.", exJa: "その後の出来事が彼の正しさを証明した。" },
    { section: "3-07", en: "estate", ja: "地所、財産、不動産", ex: "He inherited a large country estate.", exJa: "彼は広大な田舎の地所を相続した。" },
    { section: "3-07", en: "punctual", ja: "時間厳守の", ex: "Please be punctual for the meeting.", exJa: "会議には時間通りに遅れずに出席してください。" },
    { section: "3-07", en: "mercy", ja: "慈悲、寛大", ex: "They begged the enemy for mercy.", exJa: "彼らは敵に慈悲を乞うた。" },

    // Level 3-08
    { section: "3-08", en: "competence", ja: "能力、適性", ex: "He demonstrated high professional competence.", exJa: "彼は高い専門的能力を示した。" },
    { section: "3-08", en: "productive", ja: "生産的な、実りある", ex: "We had a very productive meeting.", exJa: "私たちは非常に実りある会議を行った。" },
    { section: "3-08", en: "ensure", ja: "確実にする、保証する", ex: "Please check to ensure the door is locked.", exJa: "ドアが確実に施錠されているか確認してください。" },
    { section: "3-08", en: "exclusive", ja: "独占的な、排他的な、高級な", ex: "This is an exclusive interview.", exJa: "これは独占インタビューだ。" },
    { section: "3-08", en: "mainstream", ja: "主流、主要な", ex: "His ideas have entered the mainstream.", exJa: "彼の考えは主流に入り込んできた。" },
    { section: "3-08", en: "delete", ja: "削除する", ex: "Press here to delete the file.", exJa: "ファイルを削除するにはここを押して。" },
    { section: "3-08", en: "freight", ja: "貨物、運賃", ex: "The goods were sent by air freight.", exJa: "その商品は航空貨物で送られた。" },
    { section: "3-08", en: "merchandise", ja: "商品、品物", ex: "The store sells clothing merchandise.", exJa: "その店は衣料品（商品）を販売している。" },
    { section: "3-08", en: "profession", ja: "職業、専門職", ex: "She chose the legal profession.", exJa: "彼女は法律の専門職（職業）を選んだ。" },
    { section: "3-08", en: "discard", ja: "捨てる、廃棄する", ex: "Discard old plastic bags properly.", exJa: "古いレジ袋は適切に捨てなさい。" },
    { section: "3-08", en: "expel", ja: "追放する、退学させる", ex: "The student was expelled from school.", exJa: "その生徒は学校を退学処分になった。" },
    { section: "3-08", en: "prevail", ja: "普及している、勝つ", ex: "Justice will eventually prevail.", exJa: "正義は最終的に勝つ（優勢になる）。" },
    { section: "3-08", en: "fertile", ja: "肥沃な、多産な", ex: "The valley has fertile soil for farming.", exJa: "その谷には農業に適した肥沃な土壌がある。" },
    { section: "3-08", en: "eliminate", ja: "排除する、取り除く", ex: "We must eliminate unnecessary costs.", exJa: "私たちは不必要なコストを排除しなければならない。" },
    { section: "3-08", en: "proficient", ja: "熟達した、堪能な", ex: "She is proficient in three languages.", exJa: "彼女は3か国語に堪能（熟達）だ。" },
    { section: "3-08", en: "inclusive", ja: "包括的な、含めた", ex: "The price is all-inclusive.", exJa: "その価格はすべてを含んでいる（オールインクルーシブ）。" },
    { section: "3-08", en: "vocation", ja: "天職、職業", ex: "He found his true vocation in teaching.", exJa: "彼は教育に自分の真の天職を見出した。" },
    { section: "3-08", en: "congest", ja: "混雑させる、うっ血させる", ex: "Heavy traffic congested the streets.", exJa: "激しい交通が道路を混雑させた。" },
    { section: "3-08", en: "adverse", ja: "逆の、不利な、敵意のある", ex: "The drug has adverse side effects.", exJa: "その薬には好ましくない（不利な）副作用がある。" },
    { section: "3-08", en: "expertise", ja: "専門的知識、専門技術", ex: "We lack the technical expertise.", exJa: "私たちには専門的知識が不足している。" },
    { section: "3-08", en: "retail", ja: "小売、小売りの", ex: "The retail price is higher.", exJa: "小売価格の方が高い。" },
    { section: "3-08", en: "intersection", ja: "交差点、交差", ex: "Turn left at the next intersection.", exJa: "次の交差点を左に曲がって。" },
    { section: "3-08", en: "verify", ja: "検証する、確かめる", ex: "Please verify your password.", exJa: "パスワードを確認（検証）してください。" },
    { section: "3-08", en: "contradict", ja: "矛盾する、否定する", ex: "His actions contradict his words.", exJa: "彼の行動は言動と矛盾している。" },
    { section: "3-08", en: "designate", ja: "指定する、指名する", ex: "The area was designated as a park.", exJa: "その地域は公園として指定された。" },
    { section: "3-08", en: "excerpt", ja: "抜粋、引用", ex: "Read this excerpt from the novel.", exJa: "小説からこの抜粋を読みなさい。" },
    { section: "3-08", en: "collision", ja: "衝突、激突", ex: "Two cars were involved in a collision.", exJa: "2台の車が衝突事故に巻き込まれた。" },
    { section: "3-08", en: "wholesale", ja: "卸売、卸売りの", ex: "They sell goods at wholesale prices.", exJa: "彼らは卸売価格で商品を販売している。" },
    { section: "3-08", en: "bargain", ja: "特売品、値引き交渉、安売りする", ex: "This coat was a real bargain.", exJa: "このコートは本当にお買い得品だった。" },
    { section: "3-08", en: "consumption", ja: "消費、消費量", ex: "Energy consumption is rising.", exJa: "エネルギー消費量が増加している。" },
    { section: "3-08", en: "accumulate", ja: "蓄積する、貯める", ex: "Dust accumulates quickly here.", exJa: "ここではすぐにホコリがたまる（蓄積する）。" },
    { section: "3-08", en: "aggressive", ja: "攻撃的な、積極的な", ex: "The company adopted an aggressive strategy.", exJa: "その会社は積極的な戦略を採用した。" },
    { section: "3-08", en: "accelerate", ja: "加速する、促進する", ex: "The car began to accelerate.", exJa: "車が加速し始めた。" },
    { section: "3-08", en: "abrupt", ja: "突然の、急な", ex: "There was an abrupt change in weather.", exJa: "天候の急激な変化があった。" },
    { section: "3-08", en: "adhere", ja: "固執する、付着する", ex: "Please adhere to the safety rules.", exJa: "安全規則をしっかり守る（固執する）ようにしなさい。" },
    { section: "3-08", en: "inventory", ja: "在庫、目録", ex: "We are taking inventory today.", exJa: "私たちは今日、在庫調査を行っている。" },
    { section: "3-08", en: "obscure", ja: "不明瞭な、わかりにくい、隠す", ex: "The details remain obscure.", exJa: "その詳細は不明瞭なままだ。" },
    { section: "3-08", en: "bid", ja: "入札、値をつける", ex: "He made a bid for the company.", exJa: "彼はその会社に対して買収の入札を行った。" },
    { section: "3-08", en: "certify", ja: "証明する、公認する", ex: "The documents were certified by a lawyer.", exJa: "それらの書類は弁護士によって証明された。" },
    { section: "3-08", en: "ignition", ja: "点火、イグニッション", ex: "Turn the key in the ignition.", exJa: "イグニッションの鍵を回して。" },
    { section: "3-08", en: "obsolete", ja: "すたれた、時代遅れの", ex: "Floppy disks are now obsolete.", exJa: "フロッピーディスクは今や時代遅れだ。" },
    { section: "3-08", en: "overtake", ja: "追い抜く、襲う", ex: "He overtook the car ahead.", exJa: "彼は前方の車を追い抜いた。" },
    { section: "3-08", en: "assure", ja: "保証する、安心させる", ex: "I assure you everything will be fine.", exJa: "すべてうまくいくと保証します。" },
    { section: "3-08", en: "barren", ja: "不毛の、実を結ばない", ex: "Nothing grows on this barren land.", exJa: "この不毛の土地には何も育たない。" },
    { section: "3-08", en: "hostile", ja: "敵意のある、不都合な", ex: "They faced hostile questioning.", exJa: "彼らは敵意ある質問に直面した。" },
    { section: "3-08", en: "compartment", ja: "区画、個室、仕切り", ex: "Put your bag in the overhead compartment.", exJa: "荷物は頭上の収納棚（コンパートメント）に入れなさい。" },
    { section: "3-08", en: "vessel", ja: "船、容器、血管", ex: "A large cargo vessel entered the port.", exJa: "大型貨物船が港に入港した。" },
    { section: "3-08", en: "defect", ja: "欠陥、欠点", ex: "The product had a manufacturing defect.", exJa: "その製品には製造上の欠陥があった。" },
    { section: "3-08", en: "contrary", ja: "反対の、正反対", ex: "To the contrary, I enjoyed it.", exJa: "それどころか、私はそれを楽しんだ。" },
    { section: "3-08", en: "strain", ja: "負担、緊張、ピンと張る", ex: "The work puts a strain on your eyes.", exJa: "その仕事は目に大きな負担をかける。" },

    // Level 3-09
    { section: "3-09", en: "shrink", ja: "縮む、縮小する", ex: "This wool sweater will shrink in hot water.", exJa: "このウールのセーターは熱いお湯で縮む。" },
    { section: "3-09", en: "tempt", ja: "誘惑する、仕向ける", ex: "Don't tempt me with sweets.", exJa: "甘いもので私を誘惑しないで。" },
    { section: "3-09", en: "arrogant", ja: "傲慢な、横柄な", ex: "He is arrogant and boastful.", exJa: "彼は傲慢で自慢たらしい。" },
    { section: "3-09", en: "humble", ja: "謙虚な、卑しい", ex: "Be humble despite your success.", exJa: "成功しても謙虚でありなさい。" },
    { section: "3-09", en: "diminish", ja: "減少する、衰える", ex: "His influence began to diminish.", exJa: "彼の影響力が衰え始めた。" },
    { section: "3-09", en: "initiative", ja: "主導権、自発性", ex: "She took the initiative in the project.", exJa: "彼女がそのプロジェクトで主導権を握った。" },
    { section: "3-09", en: "abolish", ja: "廃止する", ex: "The country decided to abolish the law.", exJa: "その国はその法律を廃止することを決めた。" },
    { section: "3-09", en: "modest", ja: "控えめな、謙虚な", ex: "He lives a modest lifestyle.", exJa: "彼は控えめなライフスタイルを送っている。" },
    { section: "3-09", en: "obedient", ja: "従順な、素直な", ex: "The dog is well-trained and obedient.", exJa: "その犬はよくしつけられていて従順だ。" },
    { section: "3-09", en: "decent", ja: "まともな、きちんとした", ex: "Everyone deserves a decent wage.", exJa: "誰もがまともな賃金を受け取る権利がある。" },
    { section: "3-09", en: "clumsy", ja: "不器用な、ぎこちない", ex: "I am clumsy with my hands.", exJa: "私は手先が不器用だ。" },
    { section: "3-09", en: "infinite", ja: "無限の、計り知れない", ex: "Space is practically infinite.", exJa: "宇宙は事実上無限だ。" },
    { section: "3-09", en: "bundle", ja: "束、包み", ex: "He carried a bundle of newspapers.", exJa: "彼は新聞の束を抱えていた。" },
    { section: "3-09", en: "stimulate", ja: "刺激する、活発にする", ex: "Reading stimulates the imagination.", exJa: "読書は想像力を刺激する。" },
    { section: "3-09", en: "constrain", ja: "制約する、束縛する", ex: "Budget cuts constrain our research.", exJa: "予算削減が私たちの研究を制約している。" },
    { section: "3-09", en: "heap", ja: "山、積み重ね", ex: "Clothes were in a heap on the floor.", exJa: "服が床に山のように積み上げられていた。" },
    { section: "3-09", en: "array", ja: "配列、ずらりと並べたもの", ex: "A wide array of choices is available.", exJa: "幅広い選択肢が用意されている。" },
    { section: "3-09", en: "consistent", ja: "一貫した、矛盾のない", ex: "Her story was consistent throughout.", exJa: "彼女の話は終始一貫していた。" },
    { section: "3-09", en: "surpass", ja: "勝る、凌ぐ", ex: "Sales surpassed expectations.", exJa: "売上が予想を上回った（凌いだ）。" },
    { section: "3-09", en: "sensible", ja: "分別のある、賢明な", ex: "That sounds like a sensible idea.", exJa: "それはとても賢明なアイデアに聞こえる。" },
    { section: "3-09", en: "competitive", ja: "競争の激しい、競争心の強い", ex: "The job market is highly competitive.", exJa: "就職市場は非常に競争が激しい。" },
    { section: "3-09", en: "ridiculous", ja: "ばかげた、おかしな", ex: "What a ridiculous excuse!", exJa: "なんてばかげた言い訳だ！" },
    { section: "3-09", en: "induce", ja: "誘発する、促す", ex: "Stress can induce headaches.", exJa: "ストレスは頭痛を誘発することがある。" },
    { section: "3-09", en: "intellectual", ja: "知的な、知性人", ex: "She has wide intellectual interests.", exJa: "彼女は知的な関心が幅広い。" },
    { section: "3-09", en: "prohibit", ja: "禁止する", ex: "Smoking is strictly prohibited.", exJa: "喫煙は厳に禁止されている。" },
    { section: "3-09", en: "numerous", ja: "多数の、数多くの", ex: "There are numerous reasons for this.", exJa: "これには数多くの理由がある。" },
    { section: "3-09", en: "animate", ja: "活気づける、生き生きさせる", ex: "His presence animated the party.", exJa: "彼の存在がパーティーを活気づけた。" },
    { section: "3-09", en: "halt", ja: "停止、休止、立ち止まる", ex: "Production came to a halt.", exJa: "生産が停止（ストップ）した。" },
    { section: "3-09", en: "considerate", ja: "思いやりのある、気配りのできる", ex: "It was considerate of you to help.", exJa: "手伝ってくれるなんて、君は思いやりがあるね。" },
    { section: "3-09", en: "refrain", ja: "控える、慎む", ex: "Please refrain from talking in the library.", exJa: "図書館内ではお静かに（私語を慎んで）ください。" },
    { section: "3-09", en: "prominent", ja: "卓越した、目立つ", ex: "He is a prominent scientist.", exJa: "彼は著名な（卓越した）科学者だ。" },
    { section: "3-09", en: "awkward", ja: "気まずい、不器用な", ex: "An awkward silence filled the room.", exJa: "気まずい沈黙が部屋を満たした。" },
    { section: "3-09", en: "prompt", ja: "迅速な、促す、刺激する", ex: "Please give a prompt reply.", exJa: "迅速な返信をお願いします。" },
    { section: "3-09", en: "attribute", ja: "起因すると考える、属性、特性", ex: "She attributed her success to hard work.", exJa: "彼女は自分の成功は猛勉強のおかげだと考えた。" },
    { section: "3-09", en: "brilliant", ja: "素晴らしい、輝かしい、優秀な", ex: "That was a brilliant performance.", exJa: "それは素晴らしいパフォーマンスだった。" },
    { section: "3-09", en: "restrain", ja: "制止する、抑える", ex: "He tried to restrain his anger.", exJa: "彼は怒りを抑えようとした。" },
    { section: "3-09", en: "scarcely", ja: "ほとんど〜ない", ex: "I could scarcely hear his voice.", exJa: "彼の声はほとんど聞こえなかった。" },
    { section: "3-09", en: "vigorous", ja: "精力的な、元気な", ex: "They engaged in vigorous debate.", exJa: "彼らは精力的な議論を行った。" },
    { section: "3-09", en: "confine", ja: "閉じ込める、限定する", ex: "Please confine your remarks to the topic.", exJa: "発言はそのトピックだけに限定してください。" },
    { section: "3-09", en: "indifferent", ja: "無関心な、どうでもよい", ex: "He is indifferent to politics.", exJa: "彼は政治に関心がない。" },
    { section: "3-09", en: "adequate", ja: "十分な、適切な", ex: "The room is adequate for our needs.", exJa: "その部屋は私たちのニーズに十分適している。" },
    { section: "3-09", en: "approximately", ja: "およそ、約", ex: "It takes approximately two hours.", exJa: "およそ2時間かかります。" },
    { section: "3-09", en: "eloquent", ja: "雄弁な、感情を豊かに表す", ex: "She gave an eloquent speech.", exJa: "彼女は雄弁なスピーチを行った。" },
    { section: "3-09", en: "lessen", ja: "減らす、減少させる", ex: "Medicine helps lessen the pain.", exJa: "薬が痛みを和らげる（減らす）のに役立つ。" },
    { section: "3-09", en: "boost", ja: "高める、押し上げる、増加", ex: "The win will boost team morale.", exJa: "その勝利がチームの士気を高めるだろう。" },

    // Level 3-10
    { section: "3-10", en: "manipulate", ja: "操る、巧みに扱う", ex: "He knows how to manipulate data.", exJa: "彼はデータを巧みに扱う方法を知っている。" },
    { section: "3-10", en: "predominant", ja: "優勢な、卓越した", ex: "English is the predominant language here.", exJa: "ここでは英語が優勢な言語だ。" },
    { section: "3-10", en: "valid", ja: "有効な、妥当な", ex: "This ticket is valid for one month.", exJa: "このチケットは1か月間有効だ。" },
    { section: "3-10", en: "distort", ja: "歪める、曲解する", ex: "The lens distorted the image.", exJa: "レンズが画像をゆがめた。" },
    { section: "3-10", en: "conform", ja: "従う、順応する", ex: "You must conform to the rules.", exJa: "あなたは規則に従わなければならない。" },
    { section: "3-10", en: "blunt", ja: "鈍い、率直な、切れ味の悪い", ex: "He gave a blunt answer.", exJa: "彼は率直な（ズバッとした）返事をした。" },
    { section: "3-10", en: "firsthand", ja: "直接の、直接得た", ex: "I have firsthand experience.", exJa: "私には直接経験したこと（直接の経験）がある。" },
    { section: "3-10", en: "coverage", ja: "報道、取材範囲、補償範囲", ex: "The news coverage was fair.", exJa: "そのニュースの報道は公正だった。" },
    { section: "3-10", en: "federal", ja: "連邦の", ex: "The FBI is a federal agency.", exJa: "FBIは連邦機関だ。" },
    { section: "3-10", en: "transmit", ja: "送信する、伝達する", ex: "Data is transmitted via satellite.", exJa: "データは衛星経由で送信される。" },
    { section: "3-10", en: "archive", ja: "公文書、アーカイブ、記録保管する", ex: "The documents are kept in the archive.", exJa: "それらの文書はアーカイブに保管されている。" },
    { section: "3-10", en: "specify", ja: "明確に指定する、詳述する", ex: "Please specify your preferred color.", exJa: "希望の色を明確に指定してください。" },
    { section: "3-10", en: "democratic", ja: "民主主義の、民主的な", ex: "We live in a democratic society.", exJa: "私たちは民主主義社会に生きている。" },
    { section: "3-10", en: "timid", ja: "臆病な、気弱な", ex: "The timid cat hid under the bed.", exJa: "臆病な猫がベッドの下に隠れた。" },
    { section: "3-10", en: "brochure", ja: "パンフレット、小冊子", ex: "Pick up a travel brochure.", exJa: "旅行のパンフレットを手に取ってみて。" },
    { section: "3-10", en: "commission", ja: "委員会、委託、手数料", ex: "She works on commission.", exJa: "彼女は出来高払い（手数料）で働いている。" },
    { section: "3-10", en: "duplicate", ja: "複写する、複製、副本", ex: "Make a duplicate of this key.", exJa: "この鍵の複製を作って。" },
    { section: "3-10", en: "explicit", ja: "明白な、露骨な", ex: "Give me explicit instructions.", exJa: "私にわかりやすい（明白な）指示を与えてくれ。" },
    { section: "3-10", en: "revenue", ja: "歳入、収益", ex: "The company's revenue increased.", exJa: "その会社の収益が増加した。" },
    { section: "3-10", en: "liable", ja: "法的責任がある、〜しがちである", ex: "You are liable for any damage.", exJa: "あなたにはすべての損害に対する法的責任がある。" },
    { section: "3-10", en: "reveal", ja: "明かす、暴露する", ex: "She refused to reveal the secret.", exJa: "彼女はその秘密を明かすのを拒んだ。" },
    { section: "3-10", en: "bureau", ja: "局、案内所、事務局", ex: "He works for a news bureau.", exJa: "彼は報道局で働いている。" },
    { section: "3-10", en: "compile", ja: "編集する、収集する", ex: "We are compiling a list of names.", exJa: "私たちは名前のリストを収集（編集）している。" },
    { section: "3-10", en: "hasty", ja: "急ぎの、軽率な", ex: "Don't make hasty decisions.", exJa: "軽率な決断を下してはいけない。" },
    { section: "3-10", en: "commentary", ja: "解説、論評", ex: "He provides sports commentary.", exJa: "彼はスポーツの解説を務めている。" },
    { section: "3-10", en: "notify", ja: "通知する、知らせる", ex: "Please notify us of any changes.", exJa: "変更があった場合は私たちに通知してください。" },
    { section: "3-10", en: "fluid", ja: "流体、流動的な", ex: "Plans remain fluid at this stage.", exJa: "現段階では計画は流動的だ。" },
    { section: "3-10", en: "anonymous", ja: "匿名の", ex: "The donation was made by an anonymous donor.", exJa: "その寄付は匿名の人によって行われた。" },
    { section: "3-10", en: "temper", ja: "気性、機嫌、和らげる", ex: "He has a quick temper.", exJa: "彼は短気（怒りっぽい気性）だ。" },
    { section: "3-10", en: "censorship", ja: "検閲", ex: "The book was banned due to censorship.", exJa: "その本は検閲により発禁処分になった。" },
    { section: "3-10", en: "constitution", ja: "憲法、構造、体質", ex: "The country adopted a new constitution.", exJa: "その国は新しい憲法を採択した。" },
    { section: "3-10", en: "fundamental", ja: "基本的な、根本的な", ex: "Honesty is of fundamental importance.", exJa: "正直さは根本的に重要だ。" },
    { section: "3-10", en: "characteristic", ja: "特徴、特有の", ex: "Generosity is his main characteristic.", exJa: "寛大さが彼の主な特徴だ。" },
    { section: "3-10", en: "liberal", ja: "自由主義の、寛大な", ex: "He holds liberal views.", exJa: "彼はリベラル（自由主義）な見解を持っている。" },
    { section: "3-10", en: "compliance", ja: "（規則などの）遵守、従うこと", ex: "Strict compliance with rules is required.", exJa: "規則の厳格な遵守が求められる。" },
    { section: "3-10", en: "legislation", ja: "法律、立法", ex: "New legislation was passed today.", exJa: "新しい法律が今日可決された。" },
    { section: "3-10", en: "draft", ja: "下書き、草案、徴兵する", ex: "I am working on the first draft.", exJa: "私は最初の草案に取り組んでいる。" },
    { section: "3-10", en: "rule", ja: "規則、支配、統治する", ex: "They lived under foreign rule.", exJa: "彼らは外国の支配下で暮らしていた。" },
    { section: "3-10", en: "vulnerable", ja: "傷つきやすい、脆弱な", ex: "Children are vulnerable to illness.", exJa: "子供は病気に対して脆弱（傷つきやすい）だ。" },
    { section: "3-10", en: "stubborn", ja: "頑固な、不屈の", ex: "Why are you so stubborn?", exJa: "どうしてそんなに頑固なの？" },
    { section: "3-10", en: "monarch", ja: "君主、国王", ex: "The monarch addressed the nation.", exJa: "君主が国民に向けて演説した。" },
    { section: "3-10", en: "clarify", ja: "明確にする、解明する", ex: "Let me clarify this point.", exJa: "この点を明確にさせてください。" },
    { section: "3-10", en: "regulation", ja: "規則、規制", ex: "Safety regulations must be followed.", exJa: "安全規制は守られなければならない。" },
    { section: "3-10", en: "sturdy", ja: "頑丈な、たくましい", ex: "The table is made of sturdy wood.", exJa: "そのテーブルは頑丈な木材でできている。" },
    { section: "3-10", en: "daring", ja: "大胆な、勇気のある", ex: "It was a daring rescue mission.", exJa: "それは大胆な救出作戦だった。" },
    { section: "3-10", en: "deliberate", ja: "意図的な、慎重な、熟考する", ex: "The damage was deliberate.", exJa: "その損害は意図的なものだった。" },
    { section: "3-10", en: "passive", ja: "受動的な、消極的な", ex: "He played a passive role.", exJa: "彼は消極的な役割を果たした。" },
    { section: "3-10", en: "loyal", ja: "忠実な、誠実な", ex: "She is a loyal friend.", exJa: "彼女は忠実な友人だ。" },
    { section: "3-10", en: "legitimate", ja: "合法的な、正当な", ex: "He has a legitimate reason.", exJa: "彼には正当な理由がある。" },
    { section: "3-10", en: "royalty", ja: "王族、著作権使用料", ex: "The author receives high royalties.", exJa: "その著者は多額のロイヤルティ（著作権使用料）を受け取っている。" },
    { section: "3-10", en: "congress", ja: "議会、国会", ex: "Congress approved the budget.", exJa: "議会が予算を承認した。" },
    { section: "3-10", en: "amendment", ja: "修正、改正", ex: "The constitution needs an amendment.", exJa: "その憲法には改正が必要だ。" },
    { section: "3-10", en: "negligent", ja: "怠慢な、不注意な", ex: "He was negligent in his duties.", exJa: "彼は職務において怠慢だった。" },
    { section: "3-10", en: "optimistic", ja: "楽観的な", ex: "She remains optimistic about the future.", exJa: "彼女は将来について楽観的なままだ。" },
    { section: "3-10", en: "stiff", ja: "硬い、凝った、堅苦しい", ex: "My neck is very stiff today.", exJa: "今日は首がひどく凝っている（硬い）。" },
    { section: "3-10", en: "tolerant", ja: "寛容な、耐性のある", ex: "We must be tolerant of others.", exJa: "私たちは他者に対して寛容でなければならない。" },
    { section: "3-10", en: "dominate", ja: "支配する、優勢である", ex: "The team dominated the game.", exJa: "そのチームが試合を完全に支配した。" },
    { section: "3-10", en: "naïve", ja: "世間知らずの、素朴な", ex: "It was naïve of me to trust him.", exJa: "彼を信用するなんて私は世間知らずだった。" },

    // Level 3-11
    { section: "3-11", en: "supplement", ja: "補足、サプリメント、補う", ex: "I take a daily vitamin supplement.", exJa: "私は毎日のビタミンサプリメントを摂っている。" },
    { section: "3-11", en: "conceal", ja: "隠す、秘密にする", ex: "He tried to conceal his disappointment.", exJa: "彼はがっかりした様子を隠そうとした。" },
    { section: "3-11", en: "collaborate", ja: "協力する、共同制作する", ex: "The artists agreed to collaborate.", exJa: "アーティストたちは共同制作することに合意した。" },
    { section: "3-11", en: "fraud", ja: "詐欺、不正行為", ex: "He was charged with credit card fraud.", exJa: "彼はクレジットカード詐欺で起訴された。" },
    { section: "3-11", en: "complement", ja: "補完する、引き立てる、補足", ex: "Wine complements the meal well.", exJa: "ワインが料理の味を引き立てる。" },
    { section: "3-11", en: "inspection", ja: "検査、査察", ex: "The factory undergoes safety inspections.", exJa: "その工場は安全検査を受けている。" },
    { section: "3-11", en: "dwell", ja: "住む、居住する", ex: "They dwell in a remote village.", exJa: "彼らは人里離れた村に住んでいる。" },
    { section: "3-11", en: "livelihood", ja: "生計、暮らし", ex: "Fishing is their main livelihood.", exJa: "漁業が彼らの主な生計の手段だ。" },
    { section: "3-11", en: "snatch", ja: "ひったくる、奪い取る", ex: "A thief tried to snatch her bag.", exJa: "泥棒が彼女のバッグをひったくろうとした。" },
    { section: "3-11", en: "exploit", ja: "開発する、搾取する、功績", ex: "Companies exploit natural resources.", exJa: "企業は天然資源を開発（あるいは搾取）する。" },
    { section: "3-11", en: "drowsy", ja: "眠気のする、眠い", ex: "This medicine makes me drowsy.", exJa: "この薬を飲むと眠気がする。" },
    { section: "3-11", en: "trespass", ja: "不法侵入する", ex: "Private property: Do not trespass.", exJa: "私有地につき、不法侵入禁止。" },
    { section: "3-11", en: "sneak", ja: "こっそり歩く、忍び込む", ex: "He sneaked into the theater.", exJa: "彼は映画館にこっそり忍び込んだ。" },
    { section: "3-11", en: "cram", ja: "詰め込む、詰め込み勉強する", ex: "Students cram for exams.", exJa: "学生たちは試験のために詰め込み勉強をする。" },
    { section: "3-11", en: "breach", ja: "違反、不履行、破る", ex: "It was a breach of contract.", exJa: "それは契約違反だった。" },
    { section: "3-11", en: "poll", ja: "投票、世論調査、投票を行う", ex: "The latest poll shows a close race.", exJa: "最新の世論調査では接戦が示されている。" },
    { section: "3-11", en: "trivial", ja: "ささいな、くだらない", ex: "Don't argue over trivial matters.", exJa: "ささいなことで口論するな。" },
    { section: "3-11", en: "counterpart", ja: "相当する人（もの）、対応物", ex: "He met with his French counterpart.", exJa: "彼はフランス側の対応する閣僚（同僚）と会談した。" },
    { section: "3-11", en: "disguise", ja: "変装する、偽る、変装", ex: "He wore a disguise to hide his identity.", exJa: "彼は身元を隠すために変装した。" },
    { section: "3-11", en: "unconscious", ja: "無意識の、意識を失った", ex: "He was knocked unconscious.", exJa: "彼は殴られて意識を失った。" },
    { section: "3-11", en: "deception", ja: "欺瞞、だますこと", ex: "His success was built on deception.", exJa: "彼の成功はだまし（欺瞞）のうえに成り立っていた。" },
    { section: "3-11", en: "flaw", ja: "欠陥、きず", ex: "There is a flaw in your logic.", exJa: "君の論理には欠陥がある。" },
    { section: "3-11", en: "correspond", ja: "一致する、文通する、相当する", ex: "Your story does not correspond with facts.", exJa: "君の話は事実と一致しない。" },
    { section: "3-11", en: "chore", ja: "雑用、日課", ex: "Doing laundry is my daily chore.", exJa: "洗濯は私の毎日の日課（雑用）だ。" },
    { section: "3-11", en: "ethics", ja: "倫理、道徳", ex: "Business ethics are important.", exJa: "ビジネス倫理は重要だ。" },
    { section: "3-11", en: "pastime", ja: "気晴らし、娯楽", ex: "Reading is her favorite pastime.", exJa: "読書は彼女の一番の娯楽だ。" },
    { section: "3-11", en: "classify", ja: "分類する", ex: "Books are classified by subject.", exJa: "本は主題ごとに分類されている。" },
    { section: "3-11", en: "violation", ja: "違反、侵害", ex: "It is a violation of human rights.", exJa: "それは人権侵害だ。" },
    { section: "3-11", en: "mutual", ja: "相互の、共通の", ex: "They have a mutual respect for each other.", exJa: "彼らは互いに敬意を抱いている（相互の敬意）。" },
    { section: "3-11", en: "reconcile", ja: "和解させる、調和させる", ex: "They managed to reconcile their differences.", exJa: "彼らは何とか意見の食い違いを和解させた。" },
    { section: "3-11", en: "scope", ja: "範囲、領域、機会", ex: "This is beyond the scope of our study.", exJa: "これは私たちの研究の範囲外だ。" },
    { section: "3-11", en: "accord", ja: "一致、合意、調和する", ex: "The two sides reached an accord.", exJa: "両者は合意に達した。" },
    { section: "3-11", en: "addict", ja: "中毒者、熱中する人、中毒させる", ex: "He is a computer game addict.", exJa: "彼はコンピューターゲーム中毒者だ。" },
    { section: "3-11", en: "insight", ja: "洞察力、見識", ex: "The book offers deep insight into human nature.", exJa: "その本は人間本性についての深い洞察を与えてくれる。" },
    { section: "3-11", en: "seize", ja: "つかむ、押収する、占領する", ex: "Police seized illegal drugs.", exJa: "警察が違法薬物を押収した。" },
    { section: "3-11", en: "detergent", ja: "洗剤", ex: "Use mild laundry detergent.", exJa: "肌に優しい洗濯用洗剤を使いなさい。" },
    { section: "3-11", en: "incorporate", ja: "組み込む、法人化する", ex: "We should incorporate these ideas.", exJa: "私たちはこれらのアイデアを組み込むべきだ。" },
    { section: "3-11", en: "invade", ja: "侵略する、侵入する", ex: "The army invaded neighboring lands.", exJa: "軍隊が隣国に侵略した。" },
    { section: "3-11", en: "pursue", ja: "追跡する、追求する", ex: "She wants to pursue a career in law.", exJa: "彼女は法律の分野でのキャリアを追求したいと思っている。" },
    { section: "3-11", en: "corrupt", ja: "腐敗した、買収された、堕落させる", ex: "Power can corrupt people.", exJa: "権力は人を堕落させることがある。" },
    { section: "3-11", en: "cozy", ja: "居心地の良い、快適な", ex: "The cabin was warm and cozy.", exJa: "そのキャビンは暖かくて居心地がよかった。" },
    { section: "3-11", en: "assault", ja: "暴行、攻撃、襲撃する", ex: "He was arrested for assault.", exJa: "彼は暴行罪で逮捕された。" },
    { section: "3-11", en: "psychology", ja: "心理学、心理", ex: "She studies child psychology.", exJa: "彼女は児童心理学を勉強している。" },
    { section: "3-11", en: "stain", ja: "汚れ、しみ、汚す", ex: "The coffee left a stain on the shirt.", exJa: "コーヒーがシャツにしみを残した。" },
    { section: "3-11", en: "bribe", ja: "賄賂、賄賂を贈る", ex: "He accepted a bribe to stay quiet.", exJa: "彼は黙っていることの対価として賄賂を受け取った。" },
    { section: "3-11", en: "relevant", ja: "関連のある、妥当な", ex: "Give me all relevant information.", exJa: "関連する情報をすべて私に教えてください。" },
    { section: "3-11", en: "perspective", ja: "視点、大局観、遠近法", ex: "Try to look at it from another perspective.", exJa: "別の視点からそれを見るようにしなさい。" },
    { section: "3-11", en: "habitual", ja: "習慣的な、常習的な", ex: "Lying has become his habitual behavior.", exJa: "嘘をつくことが彼の常習的な行動になってしまった。" },
    { section: "3-11", en: "integrate", ja: "統合する、融合する", ex: "Integrate theory with practice.", exJa: "理論を実践と統合しなさい。" },

    // Level 3-12
    { section: "3-12", en: "partition", ja: "分割、仕切り、分割する", ex: "A glass partition separated the rooms.", exJa: "ガラスの仕切りが部屋を区切っていた。" },
    { section: "3-12", en: "notable", ja: "注目すべき、顕著な", ex: "There was a notable increase in sales.", exJa: "売上に注目すべき（顕著な）増加があった。" },
    { section: "3-12", en: "reluctant", ja: "気の進まない、嫌々な", ex: "He was reluctant to admit his mistake.", exJa: "彼は自分の間違いを認めるのを渋っていた（気が進まなかった）。" },
    { section: "3-12", en: "preoccupied", ja: "夢中になった、心を奪われた", ex: "She was preoccupied with her work.", exJa: "彼女は仕事に夢中になっていた。" },
    { section: "3-12", en: "disgusting", ja: "むかつくような、不愉快な", ex: "The food tasted disgusting.", exJa: "その食べ物は吐き気がするほどまずかった。" },
    { section: "3-12", en: "majestic", ja: "威厳のある、荘厳な", ex: "We admired the majestic mountains.", exJa: "私たちは荘厳な山々に見とれた。" },
    { section: "3-12", en: "equivalent", ja: "同等の、相当するもの", ex: "Ten dollars is equivalent to 1,500 yen.", exJa: "10ドルは1,500円に相当する。" },
    { section: "3-12", en: "assess", ja: "評価する、査定する", ex: "Experts will assess the damage.", exJa: "専門家が被害を査定する。" },
    { section: "3-12", en: "archaeology", ja: "考古学", ex: "He is a professor of archaeology.", exJa: "彼は考古学の教授だ。" },
    { section: "3-12", en: "proportion", ja: "割合、均衡、部分", ex: "A large proportion of the budget is spent on rent.", exJa: "予算の大部分（大きな割合）が家賃に費やされている。" },
    { section: "3-12", en: "seclude", ja: "隔離する、引きこもらせる", ex: "He likes to seclude himself in his study.", exJa: "彼は書斎にこもるのが好きだ。" },
    { section: "3-12", en: "mock", ja: "あざ笑う、まねる、模擬の", ex: "Don't mock other people.", exJa: "他の人をあざ笑ってはいけない。" },
    { section: "3-12", en: "grumble", ja: "不平を言う、ぐち", ex: "He always grumbles about his job.", exJa: "彼はいつも仕事の愚痴をこぼしている。" },
    { section: "3-12", en: "accommodate", ja: "収容する、適応させる、もてなす", ex: "The hotel can accommodate 500 guests.", exJa: "そのホテルは500人のゲストを収容できる。" },
    { section: "3-12", en: "significant", ja: "重要な、かなりの、意味深な", ex: "There is a significant difference.", exJa: "そこには重要な（かなりの）違いがある。" },
    { section: "3-12", en: "credible", ja: "信用できる、信頼できる", ex: "She gave a credible explanation.", exJa: "彼女は信用できる説明をしてくれた。" },
    { section: "3-12", en: "yearn", ja: "切望する、憧れる", ex: "He yearns for peace and quiet.", exJa: "彼は平穏な暮らしを切望している。" },
    { section: "3-12", en: "detach", ja: "切り離す、取り外す", ex: "Detach the coupon from the ticket.", exJa: "チケットからクーポンを切り離しなさい。" },
    { section: "3-12", en: "evaluate", ja: "評価する、査定する", ex: "Teachers evaluate student performance.", exJa: "教師は生徒の成績を評価する。" },
    { section: "3-12", en: "absurd", ja: "ばかげた、不合理な", ex: "That is an absurd idea.", exJa: "それはばかげたアイデアだ。" },
    { section: "3-12", en: "keen", ja: "熱心な、鋭い、激しい", ex: "He is keen on photography.", exJa: "彼は写真撮影に熱心だ。" },
    { section: "3-12", en: "excursion", ja: "小旅行、遠足", ex: "We went on a day excursion to the coast.", exJa: "私たちは海岸へ日帰り旅行に出かけた。" },
    { section: "3-12", en: "decisive", ja: "決定的な、断固とした", ex: "This was a decisive moment in history.", exJa: "これは歴史上の決定的な瞬間だった。" },
    { section: "3-12", en: "weary", ja: "疲れ果てた、うんざりした", ex: "He looked weary after the long journey.", exJa: "長い旅の後で、彼は疲れ果てて見えた。" },
    { section: "3-12", en: "desperate", ja: "絶望的な、必死の、欲しくてたまらない", ex: "She made a desperate attempt to escape.", exJa: "彼女は必死の脱出を試みた。" },
    { section: "3-12", en: "conquer", ja: "征服する、克服する", ex: "You must conquer your fear.", exJa: "君は自分の恐怖を克服しなければならない。" },
    { section: "3-12", en: "itinerary", ja: "旅行日程、旅程", ex: "Check your travel itinerary.", exJa: "旅行日程表を確認しなさい。" },
    { section: "3-12", en: "notorious", ja: "悪名高い", ex: "The city is notorious for traffic jams.", exJa: "その街は交通渋滞が悪名高い。" },
    { section: "3-12", en: "monotonous", ja: "単調な、退屈な", ex: "His daily routine is monotonous.", exJa: "彼の毎日の日課は単調だ。" },
    { section: "3-12", en: "spectacle", ja: "見世物、壮観、眼鏡", ex: "The sunset was a magnificent spectacle.", exJa: "夕日は見事な壮観だった。" },
    { section: "3-12", en: "sophisticated", ja: "洗練された、高度な", ex: "She has sophisticated tastes.", exJa: "彼女は洗練された趣味を持っている。" },
    { section: "3-12", en: "intense", ja: "強烈な、熱烈な", ex: "The heat was intense today.", exJa: "今日の暑さは強烈だった。" },
    { section: "3-12", en: "disregard", ja: "無視する、軽視する", ex: "Do not disregard safety warnings.", exJa: "安全警告を無視してはならない。" },
    { section: "3-12", en: "deprive", ja: "奪う、剥奪する", ex: "Sleep deprivation deprives you of energy.", exJa: "睡眠不足はエネルギーを奪う。" },
    { section: "3-12", en: "exotic", ja: "異国風の、外来の", ex: "She loves exotic flowers.", exJa: "彼女は異国風の花が好きだ。" },
    { section: "3-12", en: "indulge", ja: "浸る、甘わせる、思う存分楽しむ", ex: "He likes to indulge in sweets.", exJa: "彼は甘いものに目がない（思いっきり楽しむのが好きだ）。" },
    { section: "3-12", en: "fraction", ja: "少量、端数、分数", ex: "Only a fraction of the cost.", exJa: "費用のほんのわずかな一部（少量）にすぎない。" },
    { section: "3-12", en: "impulse", ja: "衝動、刺激", ex: "I bought the shoes on impulse.", exJa: "その靴は衝動買いしてしまった。" },
    { section: "3-12", en: "attain", ja: "達成する、手に入れる", ex: "Hard work helps you attain your goals.", exJa: "努力は目標を達成するのに役立つ。" },
    { section: "3-12", en: "tangible", ja: "明白な、実体のある、触れることができる", ex: "There is no tangible evidence.", exJa: "目に見える（実体のある）証拠はない。" },
    { section: "3-12", en: "segment", ja: "部分、区分、分割する", ex: "A large segment of the population agrees.", exJa: "人口の大規模な区分（層）が同意している。" },
    { section: "3-12", en: "partial", ja: "部分的な、不完全な、ひいきする", ex: "I only have partial information.", exJa: "私は部分的な情報しか持っていない。" },
    { section: "3-12", en: "disgrace", ja: "不名誉、恥、面目をつぶす", ex: "His actions brought disgrace to his family.", exJa: "彼の行動は家族に不名誉をもたらした。" },
    { section: "3-12", en: "overwhelming", ja: "圧倒的な", ex: "There was overwhelming support.", exJa: "圧倒的な支持が集まった。" },
    { section: "3-12", en: "tranquil", ja: "穏やかな、静かな", ex: "We enjoyed a tranquil afternoon.", exJa: "私たちは穏やかな午後を楽しんだ。" },
    { section: "3-12", en: "neglect", ja: "放置する、怠る、無視", ex: "Do not neglect your studies.", exJa: "勉強を怠ってはいけない。" },
    { section: "3-12", en: "elaborate", ja: "手の込んだ、詳しく述べる", ex: "She made an elaborate plan.", exJa: "彼女は手の込んだ計画を立てた。" },
    { section: "3-12", en: "authentic", ja: "本物の、信頼できる", ex: "This is an authentic painting.", exJa: "これは本物の絵画だ。" },
    { section: "3-12", en: "inclination", ja: "傾向、意向、傾き", ex: "I have no inclination to argue.", exJa: "私には言い争う気（意向）はない。" },
    { section: "3-12", en: "torture", ja: "拷問、苦痛、拷問する", ex: "Prisoners suffered torture.", exJa: "囚人たちは拷問の苦痛を受けた。" },
    { section: "3-12", en: "pessimistic", ja: "悲観的な", ex: "Don't be so pessimistic.", exJa: "そんなに悲観的にならないで。" },
    { section: "3-12", en: "component", ja: "構成要素、部品", ex: "Engine is a vital component of a car.", exJa: "エンジンは車の極めて重要な構成要素だ。" },
    { section: "3-12", en: "void", ja: "空虚な、無効な、空間、無効", ex: "The contract is null and void.", exJa: "その契約は無効だ。" },
    { section: "3-12", en: "sob", ja: "すすり泣く、泣きじゃくる", ex: "The child began to sob.", exJa: "子供がすすり泣き始めた。" },
    { section: "3-12", en: "irritate", ja: "いらだたせる、怒らせる", ex: "His loud voice irritated me.", exJa: "彼の大きな声にいらだたされた。" },
    { section: "3-12", en: "peculiar", ja: "独特の、変な", ex: "I noticed a peculiar smell.", exJa: "独特の（変わった）においに気づいた。" },
    { section: "3-12", en: "disperse", ja: "分散させる、散る", ex: "Clouds began to disperse.", exJa: "雲が散り始めた。" },
    { section: "3-12", en: "dismal", ja: "陰気な、暗い、憂鬱な", ex: "The weather was dismal all day.", exJa: "一日中、天気は陰気で冴えなかった。" },
    { section: "3-12", en: "heritage", ja: "遺産、伝統", ex: "We must protect our cultural heritage.", exJa: "私たちは文化的遺産を保護しなければならない。" },
    { section: "3-12", en: "conventional", ja: "従来の、因習的な", ex: "They use conventional methods.", exJa: "彼らは従来の方法を用いている。" },
    { section: "3-12", en: "prestigious", ja: "名誉ある、一流の", ex: "He won a prestigious award.", exJa: "彼は名誉ある賞を受賞した。" },
    { section: "3-12", en: "comparative", ja: "比較の、比較的低い", ex: "We made a comparative study.", exJa: "私たちは比較研究を行った。" },
    { section: "3-12", en: "solemn", ja: "厳粛な、まじめな", ex: "They took a solemn oath.", exJa: "彼らは厳粛な誓いを立てた。" },
    { section: "3-12", en: "pathetic", ja: "哀れな、痛ましい", ex: "It is a pathetic sight.", exJa: "それは何とも哀れな光景だ。" },
    { section: "3-12", en: "scrap", ja: "破片、スクラップ、廃棄する", ex: "He wrote a note on a scrap of paper.", exJa: "彼は紙切れの端にメモを書いた。" },

    // Level 3-13
    { section: "3-13", en: "carry over", ja: "持ち越す、繰り越す", ex: "Unused days off carry over to next year.", exJa: "使わなかった休みは来年に繰り越される。" },
    { section: "3-13", en: "take on", ja: "引き受ける、採用する、帯びる", ex: "She agreed to take on the new role.", exJa: "彼女はその新しい役割を引き受けることに同意した。" },
    { section: "3-13", en: "play down", ja: "軽視する、過小評価する", ex: "The government tried to play down the crisis.", exJa: "政府はその危機を軽視させようとした。" },
    { section: "3-13", en: "lay off", ja: "一時解雇する、やめる", ex: "The company had to lay off workers.", exJa: "会社は従業員を一時解雇せざるを得なかった。" },
    { section: "3-13", en: "answer for", ja: "責任を負う、保証する", ex: "You will have to answer for your actions.", exJa: "自分の行動に対して責任を取ってもらう。" },
    { section: "3-13", en: "stick up for", ja: "擁護する、支持する", ex: "Always stick up for your friends.", exJa: "いつでも友達の味方をして（擁護して）あげなさい。" },
    { section: "3-13", en: "give off", ja: "（光・においなどを）発する、放つ", ex: "The flowers give off a sweet scent.", exJa: "その花は甘い香りを放つ。" },
    { section: "3-13", en: "hold back", ja: "抑える、隠す、躊躇する", ex: "She couldn't hold back her tears.", exJa: "彼女は涙を抑えきれなかった。" },
    { section: "3-13", en: "pass on", ja: "伝える、渡す", ex: "Please pass this message on to him.", exJa: "この伝言を彼に伝えておいてください。" },
    { section: "3-13", en: "hold out", ja: "持ちこたえる、差し出す", ex: "How long can they hold out?", exJa: "彼らはどれくらい持ちこたえられるだろうか？" },
    { section: "3-13", en: "try out", ja: "試す、試用する", ex: "Let's try out the new software.", exJa: "新しいソフトウェアを試してみよう。" },
    { section: "3-13", en: "pay off", ja: "報われる、清算する、うまくいく", ex: "All your hard work will pay off.", exJa: "これまでの努力がすべて報われるだろう。" },
    { section: "3-13", en: "toss out", ja: "投げ捨てる、追い出す", ex: "Toss out the old newspapers.", exJa: "古い新聞紙を投げ捨てなさい。" },
    { section: "3-13", en: "wear off", ja: "（効果などが）だんだん薄れる、すり減る", ex: "The painkiller will soon wear off.", exJa: "鎮痛剤の効果がまもなく薄れるだろう。" },
    { section: "3-13", en: "break off", ja: "中断する、絶交する、切り離す", ex: "They decided to break off negotiations.", exJa: "彼らは交渉を中断することを決めた。" },
    { section: "3-13", en: "break out", ja: "（戦争・病気などが）突発する、勃発する", ex: "A fire broke out during the night.", exJa: "夜間に火事が勃発した。" },
    { section: "3-13", en: "set off", ja: "引き起こす、出発する、爆発させる", ex: "The smoke set off the alarm.", exJa: "煙が警報機を作動（引き起こ）した。" },
    { section: "3-13", en: "dish out", ja: "（食事などを）配る、分け与える", ex: "She dished out the food to guests.", exJa: "彼女はゲストに食事を配った。" },
    { section: "3-13", en: "let up", ja: "（雨や苦痛などが）弱まる、手加減する", ex: "The rain finally let up.", exJa: "雨がようやく小康状態になった（弱まった）。" },
    { section: "3-13", en: "cut down on", ja: "〜を減らす、切り詰める", ex: "Cut down on sugar and fat.", exJa: "糖分と脂肪の摂取を控えなさい。" },
    { section: "3-13", en: "get around", ja: "（噂などが）広まる、回避する、動き回る", ex: "News travels fast (get around).", exJa: "噂はあっという間に広まる。" },
    { section: "3-13", en: "put down", ja: "書き留める、鎮圧する、けなす", ex: "Put down your ideas on paper.", exJa: "考えを紙に書き留めなさい。" },
    { section: "3-13", en: "pull over", ja: "（車を）脇に寄せて止める", ex: "The police officer told him to pull over.", exJa: "警察官が彼に車を脇に寄せて止めるよう指示した。" },
    { section: "3-13", en: "hammer out", ja: "（議論の末に）合意に達する、考え出す", ex: "They hammered out an agreement.", exJa: "彼らは議論の末に合意に達した。" },
    { section: "3-13", en: "stick around", ja: "そのあたりにとどまる、待機する", ex: "Wait for me and stick around.", exJa: "私を待ってそのあたりで待機していてくれ。" },
    { section: "3-13", en: "bring out", ja: "引き出す、発表する、発売する", ex: "Good teaching brings out the best in students.", exJa: "良い教育は生徒の長所を引き出す。" },
    { section: "3-13", en: "fall back on", ja: "〜を頼る、当てにする", ex: "We have savings to fall back on.", exJa: "私たちにはいざという時に頼れる貯金がある。" },
    { section: "3-13", en: "bring on", ja: "（災難などを）引き起こす、もたらす", ex: "Stress can bring on health problems.", exJa: "ストレスは健康上の問題を引き起こすことがある。" },
    { section: "3-13", en: "fall through", ja: "（計画などが）失敗する、流れる", ex: "Our vacation plans fell through.", exJa: "私たちの休暇の計画が流れてしまった（失敗した）。" },
    { section: "3-13", en: "stick with", ja: "〜を続ける、〜を見捨てない", ex: "Stick with your plan.", exJa: "自分の計画をやり続けなさい。" },
    { section: "3-13", en: "live up to", ja: "（期待などに）応える、恥じない行動をする", ex: "He lived up to his parents' expectations.", exJa: "彼は両親の期待に応えた。" },
    { section: "3-13", en: "make out", ja: "理解する、見分ける、作成する", ex: "I couldn't make out what he said.", exJa: "彼の言っていることが聞き取れ（理解でき）なかった。" },
    { section: "3-13", en: "carry through", ja: "やり通す、やり抜く", ex: "She carried the project through to the end.", exJa: "彼女はそのプロジェクトを最後までやり抜いた。" },
    { section: "3-13", en: "run through", ja: "ざっと目を通す、使い果たす", ex: "Let's run through the plan once more.", exJa: "もう一度だけ計画にざっと目を通してみよう。" },
    { section: "3-13", en: "pros and cons", ja: "賛否両論、利点と欠点", ex: "Consider the pros and cons of the offer.", exJa: "そのオファーの利点と欠点（賛否両論）をよく考えなさい。" },
    { section: "3-13", en: "set in", ja: "（季節・天候などが）始まる、定着する", ex: "The rainy season has set in.", exJa: "梅雨が本格的に始まった。" },
    { section: "3-13", en: "put through", ja: "（電話を）つなぐ、やり遂げる", ex: "Put me through to the manager, please.", exJa: "マネージャーに電話をつないでください。" },
    { section: "3-13", en: "see through", ja: "見抜く、最後までやり通す", ex: "I can see through his lies.", exJa: "彼の嘘なんてお見通しだ（見抜ける）。" },
    { section: "3-13", en: "get back to", ja: "（あとで）〜に連絡し直す、〜に戻る", ex: "I will get back to you later.", exJa: "あとであなたに連絡し直します。" },
    { section: "3-13", en: "pull out", ja: "撤退する、引き出す、車を車道に出す", ex: "The troops began to pull out.", exJa: "軍隊が撤退を始めた。" },
    { section: "3-13", en: "give out", ja: "配る、使い果たす、機能を停止する", ex: "Leaflets were given out at the station.", exJa: "駅でチラシが配られた。" },
    { section: "3-13", en: "take in", ja: "理解する、取り入れる、だます、見物する", ex: "It's hard to take in all the information.", exJa: "すべての情報を一度に理解するのは難しい。" },
    { section: "3-13", en: "stand in for", ja: "〜の代理を務める", ex: "She will stand in for the director today.", exJa: "彼女が今日ディレクターの代理を務める。" },
    { section: "3-13", en: "come down with", ja: "（病気にかかる）", ex: "He came down with a bad cold.", exJa: "彼はひどい風邪をひいた（にかかった）。" },
    { section: "3-13", en: "burn out", ja: "燃え尽きる、燃え尽きさせる、使い果たす", ex: "He worked too hard and burned out.", exJa: "彼は働きすぎて燃え尽きてしまった。" },
    { section: "3-13", en: "pass out", ja: "意識を失う、気絶する、配る", ex: "He felt dizzy and passed out.", exJa: "彼はめまいがして意識を失った。" },
    { section: "3-13", en: "shake off", ja: "（悪癖・病気・追跡者などを）振り払う、断ち切る", ex: "She couldn't shake off the flu.", exJa: "彼女はインフルエンザがなかなか治らなかった（振り払えなかった）。" },
    { section: "3-13", en: "stand apart", ja: "際立っている、一線を画す", ex: "Her work stands apart from the rest.", exJa: "彼女の作品は他とは一線を画している（際立っている）。" },
    { section: "3-13", en: "set about", ja: "~に取りかかる、着手する", ex: "They set about cleaning the house.", exJa: "彼らは家の掃除に取りかかった。" }
];
